/* tslint:disable */
/* eslint-disable */
/**
 * CrispHive Developer API
 * Public REST API for integrating CrispHive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ListSkillCategories200Response } from '../models';
// @ts-ignore
import type { ListSkills200Response } from '../models';
// @ts-ignore
import type { ListSkillsByCategory200Response } from '../models';
// @ts-ignore
import type { ResponseEnvelope } from '../models';
/**
 * BusinessSkillApi - axios parameter creator
 * @export
 */
export const BusinessSkillApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns paginated skill categories for the current business, ordered alphabetically.
         * @summary List skill categories
         * @param {number} [page] Page number (default: 1)
         * @param {number} [limit] Page size (default: 15, max: 1000)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSkillCategories: async (page?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/skill-categories`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the flat list of all active skills for the current business across every category. Use this to discover the skill UUIDs accepted in `skill_ids` when creating a job request. (For a category-grouped view, use GET /skill-categories and GET /skill-categories/{id}/skills.)
         * @summary List all skills
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSkills: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/skills`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns paginated skills belonging to the given category, ordered alphabetically. The `members` field on each skill is the count of active technicians currently assigned to it.
         * @summary List skills in a category
         * @param {string} id Skill category ID (UUID)
         * @param {number} [page] Page number (default: 1)
         * @param {number} [limit] Page size (default: 15, max: 1000)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSkillsByCategory: async (id: string, page?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('listSkillsByCategory', 'id', id)
            const localVarPath = `/skill-categories/{id}/skills`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BusinessSkillApi - functional programming interface
 * @export
 */
export const BusinessSkillApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BusinessSkillApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns paginated skill categories for the current business, ordered alphabetically.
         * @summary List skill categories
         * @param {number} [page] Page number (default: 1)
         * @param {number} [limit] Page size (default: 15, max: 1000)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listSkillCategories(page?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListSkillCategories200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listSkillCategories(page, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BusinessSkillApi.listSkillCategories']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns the flat list of all active skills for the current business across every category. Use this to discover the skill UUIDs accepted in `skill_ids` when creating a job request. (For a category-grouped view, use GET /skill-categories and GET /skill-categories/{id}/skills.)
         * @summary List all skills
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listSkills(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListSkills200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listSkills(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BusinessSkillApi.listSkills']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns paginated skills belonging to the given category, ordered alphabetically. The `members` field on each skill is the count of active technicians currently assigned to it.
         * @summary List skills in a category
         * @param {string} id Skill category ID (UUID)
         * @param {number} [page] Page number (default: 1)
         * @param {number} [limit] Page size (default: 15, max: 1000)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listSkillsByCategory(id: string, page?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListSkillsByCategory200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listSkillsByCategory(id, page, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BusinessSkillApi.listSkillsByCategory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * BusinessSkillApi - factory interface
 * @export
 */
export const BusinessSkillApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BusinessSkillApiFp(configuration)
    return {
        /**
         * Returns paginated skill categories for the current business, ordered alphabetically.
         * @summary List skill categories
         * @param {BusinessSkillApiListSkillCategoriesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSkillCategories(requestParameters: BusinessSkillApiListSkillCategoriesRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<ListSkillCategories200Response> {
            return localVarFp.listSkillCategories(requestParameters.page, requestParameters.limit, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the flat list of all active skills for the current business across every category. Use this to discover the skill UUIDs accepted in `skill_ids` when creating a job request. (For a category-grouped view, use GET /skill-categories and GET /skill-categories/{id}/skills.)
         * @summary List all skills
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSkills(options?: RawAxiosRequestConfig): AxiosPromise<ListSkills200Response> {
            return localVarFp.listSkills(options).then((request) => request(axios, basePath));
        },
        /**
         * Returns paginated skills belonging to the given category, ordered alphabetically. The `members` field on each skill is the count of active technicians currently assigned to it.
         * @summary List skills in a category
         * @param {BusinessSkillApiListSkillsByCategoryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSkillsByCategory(requestParameters: BusinessSkillApiListSkillsByCategoryRequest, options?: RawAxiosRequestConfig): AxiosPromise<ListSkillsByCategory200Response> {
            return localVarFp.listSkillsByCategory(requestParameters.id, requestParameters.page, requestParameters.limit, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for listSkillCategories operation in BusinessSkillApi.
 * @export
 * @interface BusinessSkillApiListSkillCategoriesRequest
 */
export interface BusinessSkillApiListSkillCategoriesRequest {
    /**
     * Page number (default: 1)
     * @type {number}
     * @memberof BusinessSkillApiListSkillCategories
     */
    readonly page?: number

    /**
     * Page size (default: 15, max: 1000)
     * @type {number}
     * @memberof BusinessSkillApiListSkillCategories
     */
    readonly limit?: number
}

/**
 * Request parameters for listSkillsByCategory operation in BusinessSkillApi.
 * @export
 * @interface BusinessSkillApiListSkillsByCategoryRequest
 */
export interface BusinessSkillApiListSkillsByCategoryRequest {
    /**
     * Skill category ID (UUID)
     * @type {string}
     * @memberof BusinessSkillApiListSkillsByCategory
     */
    readonly id: string

    /**
     * Page number (default: 1)
     * @type {number}
     * @memberof BusinessSkillApiListSkillsByCategory
     */
    readonly page?: number

    /**
     * Page size (default: 15, max: 1000)
     * @type {number}
     * @memberof BusinessSkillApiListSkillsByCategory
     */
    readonly limit?: number
}

/**
 * BusinessSkillApi - object-oriented interface
 * @export
 * @class BusinessSkillApi
 * @extends {BaseAPI}
 */
export class BusinessSkillApi extends BaseAPI {
    /**
     * Returns paginated skill categories for the current business, ordered alphabetically.
     * @summary List skill categories
     * @param {BusinessSkillApiListSkillCategoriesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BusinessSkillApi
     */
    public listSkillCategories(requestParameters: BusinessSkillApiListSkillCategoriesRequest = {}, options?: RawAxiosRequestConfig) {
        return BusinessSkillApiFp(this.configuration).listSkillCategories(requestParameters.page, requestParameters.limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns the flat list of all active skills for the current business across every category. Use this to discover the skill UUIDs accepted in `skill_ids` when creating a job request. (For a category-grouped view, use GET /skill-categories and GET /skill-categories/{id}/skills.)
     * @summary List all skills
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BusinessSkillApi
     */
    public listSkills(options?: RawAxiosRequestConfig) {
        return BusinessSkillApiFp(this.configuration).listSkills(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns paginated skills belonging to the given category, ordered alphabetically. The `members` field on each skill is the count of active technicians currently assigned to it.
     * @summary List skills in a category
     * @param {BusinessSkillApiListSkillsByCategoryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BusinessSkillApi
     */
    public listSkillsByCategory(requestParameters: BusinessSkillApiListSkillsByCategoryRequest, options?: RawAxiosRequestConfig) {
        return BusinessSkillApiFp(this.configuration).listSkillsByCategory(requestParameters.id, requestParameters.page, requestParameters.limit, options).then((request) => request(this.axios, this.basePath));
    }
}

