/* tslint:disable */
/* eslint-disable */
/**
 * CrispHive Developer API
 * Public REST API for integrating CrispHive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateJobRequest200Response } from '../models';
// @ts-ignore
import type { GetJobRequest200Response } from '../models';
// @ts-ignore
import type { GetJobRequestTimeline200Response } from '../models';
// @ts-ignore
import type { JobRequestCreateRequest } from '../models';
// @ts-ignore
import type { ListJobRequestBookingWindows200Response } from '../models';
// @ts-ignore
import type { ListJobRequestChanges200Response } from '../models';
// @ts-ignore
import type { ListJobRequests200Response } from '../models';
/**
 * JobRequestBusinessApi - axios parameter creator
 * @export
 */
export const JobRequestBusinessApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a job request (business actor)
         * @param {JobRequestCreateRequest} jobRequestCreateRequest Booking payload
         * @param {string} [xTimezone] Customer IANA timezone
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createJobRequest: async (jobRequestCreateRequest: JobRequestCreateRequest, xTimezone?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'jobRequestCreateRequest' is not null or undefined
            assertParamExists('createJobRequest', 'jobRequestCreateRequest', jobRequestCreateRequest)
            const localVarPath = `/job-requests`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xTimezone != null) {
                localVarHeaderParameter['X-Timezone'] = String(xTimezone);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(jobRequestCreateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a job request
         * @param {string} id Job request ID (UUID or short_code)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJobRequest: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getJobRequest', 'id', id)
            const localVarPath = `/job-requests/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Per-status events[] composed from workflow snapshot + scattered typed cols + action_audit. FE renders as the Job Timeline panel (completed step = filled check, current = outline ring, upcoming = empty). entered_at nil for upcoming steps + older jobs missing the typed-col backfill.
         * @summary Job timeline (business surface — also serves tech via BusinessAuth)
         * @param {string} id Job request ID (UUID or short_code)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJobRequestTimeline: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getJobRequestTimeline', 'id', id)
            const localVarPath = `/job-requests/{id}/timeline`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Booking availability (business actor)
         * @param {string} xTimezone Customer IANA timezone
         * @param {string} [from] Start YYYY-MM-DD
         * @param {string} [to] End YYYY-MM-DD
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listJobRequestBookingWindows: async (xTimezone: string, from?: string, to?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xTimezone' is not null or undefined
            assertParamExists('listJobRequestBookingWindows', 'xTimezone', xTimezone)
            const localVarPath = `/job-requests/booking-windows`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (from !== undefined) {
                localVarQueryParameter['from'] = from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = to;
            }


    
            if (xTimezone != null) {
                localVarHeaderParameter['X-Timezone'] = String(xTimezone);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Keep your own copy of bookings in sync WITHOUT re-listing everything: returns the job requests whose state changed (created, status transition, reschedule, soft-delete/archive) at or after the `since` cursor, ordered oldest-change-first (updated_at ASC).  How to use it: (1) On your first poll OMIT `since` — the server primes the cursor at \"now\", returns no items and a `next_since`. (2) Store `next_since` and pass it as `since` on the next poll. (3) Apply each returned item to your store by UPSERTING on `id` (the server re-scans a ~5s safety window, so the same job may appear again — never blindly append). (4) If `has_more` is true the page filled to `limit` and more changes are already waiting — poll again immediately; otherwise wait your normal interval (e.g. 5–15s).  This is NOT pagination — it is a time-keyed change feed. Use the paginated GET /job-requests for the initial bulk load, then this endpoint to stay live. Filters (status_keys, customer_id, …) narrow the feed to the slice you care about.
         * @summary Poll for new & changed job requests (sync feed)
         * @param {string} [statusKeys] Comma-separated status slugs — only surface changes to jobs in these statuses
         * @param {string} [priority] Priority filter (normal|emergency)
         * @param {string} [customerId] Only changes to this customer\&#39;s jobs (UUID)
         * @param {string} [technicianId] Only changes to jobs assigned to this technician (UUID)
         * @param {string} [scheduledFrom] Filter from (YYYY-MM-DD or RFC3339); range is [from, to)
         * @param {string} [scheduledTo] Filter to (YYYY-MM-DD or RFC3339), exclusive
         * @param {string} [since] RFC3339 cursor from the prior response\&#39;s next_since. OMIT on the first poll to prime the cursor at server-now.
         * @param {number} [limit] Max changes per poll (default 15, max 1000). If the page fills, has_more&#x3D;true.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listJobRequestChanges: async (statusKeys?: string, priority?: string, customerId?: string, technicianId?: string, scheduledFrom?: string, scheduledTo?: string, since?: string, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/job-requests/changes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (statusKeys !== undefined) {
                localVarQueryParameter['status_keys'] = statusKeys;
            }

            if (priority !== undefined) {
                localVarQueryParameter['priority'] = priority;
            }

            if (customerId !== undefined) {
                localVarQueryParameter['customer_id'] = customerId;
            }

            if (technicianId !== undefined) {
                localVarQueryParameter['technician_id'] = technicianId;
            }

            if (scheduledFrom !== undefined) {
                localVarQueryParameter['scheduled_from'] = scheduledFrom;
            }

            if (scheduledTo !== undefined) {
                localVarQueryParameter['scheduled_to'] = scheduledTo;
            }

            if (since !== undefined) {
                localVarQueryParameter['since'] = since;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List job requests
         * @param {string} [statusKeys] Comma-separated status slugs
         * @param {string} [status] active (default) | archived | all
         * @param {string} [customerId] Customer UUID
         * @param {string} [technicianId] Technician UUID
         * @param {string} [scheduledFrom] Filter from (YYYY-MM-DD or RFC3339); range is [from, to)
         * @param {string} [scheduledTo] Filter to (YYYY-MM-DD or RFC3339), exclusive
         * @param {string} [q] Search short_code or description (case-insensitive, partial match)
         * @param {string} [sort] Sort key
         * @param {number} [page] Page number
         * @param {number} [limit] Page size
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listJobRequests: async (statusKeys?: string, status?: string, customerId?: string, technicianId?: string, scheduledFrom?: string, scheduledTo?: string, q?: string, sort?: string, page?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/job-requests`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (statusKeys !== undefined) {
                localVarQueryParameter['status_keys'] = statusKeys;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (customerId !== undefined) {
                localVarQueryParameter['customer_id'] = customerId;
            }

            if (technicianId !== undefined) {
                localVarQueryParameter['technician_id'] = technicianId;
            }

            if (scheduledFrom !== undefined) {
                localVarQueryParameter['scheduled_from'] = scheduledFrom;
            }

            if (scheduledTo !== undefined) {
                localVarQueryParameter['scheduled_to'] = scheduledTo;
            }

            if (q !== undefined) {
                localVarQueryParameter['q'] = q;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * JobRequestBusinessApi - functional programming interface
 * @export
 */
export const JobRequestBusinessApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = JobRequestBusinessApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a job request (business actor)
         * @param {JobRequestCreateRequest} jobRequestCreateRequest Booking payload
         * @param {string} [xTimezone] Customer IANA timezone
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createJobRequest(jobRequestCreateRequest: JobRequestCreateRequest, xTimezone?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateJobRequest200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createJobRequest(jobRequestCreateRequest, xTimezone, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JobRequestBusinessApi.createJobRequest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a job request
         * @param {string} id Job request ID (UUID or short_code)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getJobRequest(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetJobRequest200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getJobRequest(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JobRequestBusinessApi.getJobRequest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Per-status events[] composed from workflow snapshot + scattered typed cols + action_audit. FE renders as the Job Timeline panel (completed step = filled check, current = outline ring, upcoming = empty). entered_at nil for upcoming steps + older jobs missing the typed-col backfill.
         * @summary Job timeline (business surface — also serves tech via BusinessAuth)
         * @param {string} id Job request ID (UUID or short_code)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getJobRequestTimeline(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetJobRequestTimeline200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getJobRequestTimeline(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JobRequestBusinessApi.getJobRequestTimeline']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Booking availability (business actor)
         * @param {string} xTimezone Customer IANA timezone
         * @param {string} [from] Start YYYY-MM-DD
         * @param {string} [to] End YYYY-MM-DD
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listJobRequestBookingWindows(xTimezone: string, from?: string, to?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListJobRequestBookingWindows200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listJobRequestBookingWindows(xTimezone, from, to, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JobRequestBusinessApi.listJobRequestBookingWindows']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Keep your own copy of bookings in sync WITHOUT re-listing everything: returns the job requests whose state changed (created, status transition, reschedule, soft-delete/archive) at or after the `since` cursor, ordered oldest-change-first (updated_at ASC).  How to use it: (1) On your first poll OMIT `since` — the server primes the cursor at \"now\", returns no items and a `next_since`. (2) Store `next_since` and pass it as `since` on the next poll. (3) Apply each returned item to your store by UPSERTING on `id` (the server re-scans a ~5s safety window, so the same job may appear again — never blindly append). (4) If `has_more` is true the page filled to `limit` and more changes are already waiting — poll again immediately; otherwise wait your normal interval (e.g. 5–15s).  This is NOT pagination — it is a time-keyed change feed. Use the paginated GET /job-requests for the initial bulk load, then this endpoint to stay live. Filters (status_keys, customer_id, …) narrow the feed to the slice you care about.
         * @summary Poll for new & changed job requests (sync feed)
         * @param {string} [statusKeys] Comma-separated status slugs — only surface changes to jobs in these statuses
         * @param {string} [priority] Priority filter (normal|emergency)
         * @param {string} [customerId] Only changes to this customer\&#39;s jobs (UUID)
         * @param {string} [technicianId] Only changes to jobs assigned to this technician (UUID)
         * @param {string} [scheduledFrom] Filter from (YYYY-MM-DD or RFC3339); range is [from, to)
         * @param {string} [scheduledTo] Filter to (YYYY-MM-DD or RFC3339), exclusive
         * @param {string} [since] RFC3339 cursor from the prior response\&#39;s next_since. OMIT on the first poll to prime the cursor at server-now.
         * @param {number} [limit] Max changes per poll (default 15, max 1000). If the page fills, has_more&#x3D;true.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listJobRequestChanges(statusKeys?: string, priority?: string, customerId?: string, technicianId?: string, scheduledFrom?: string, scheduledTo?: string, since?: string, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListJobRequestChanges200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listJobRequestChanges(statusKeys, priority, customerId, technicianId, scheduledFrom, scheduledTo, since, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JobRequestBusinessApi.listJobRequestChanges']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List job requests
         * @param {string} [statusKeys] Comma-separated status slugs
         * @param {string} [status] active (default) | archived | all
         * @param {string} [customerId] Customer UUID
         * @param {string} [technicianId] Technician UUID
         * @param {string} [scheduledFrom] Filter from (YYYY-MM-DD or RFC3339); range is [from, to)
         * @param {string} [scheduledTo] Filter to (YYYY-MM-DD or RFC3339), exclusive
         * @param {string} [q] Search short_code or description (case-insensitive, partial match)
         * @param {string} [sort] Sort key
         * @param {number} [page] Page number
         * @param {number} [limit] Page size
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listJobRequests(statusKeys?: string, status?: string, customerId?: string, technicianId?: string, scheduledFrom?: string, scheduledTo?: string, q?: string, sort?: string, page?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListJobRequests200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listJobRequests(statusKeys, status, customerId, technicianId, scheduledFrom, scheduledTo, q, sort, page, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JobRequestBusinessApi.listJobRequests']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * JobRequestBusinessApi - factory interface
 * @export
 */
export const JobRequestBusinessApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = JobRequestBusinessApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a job request (business actor)
         * @param {JobRequestBusinessApiCreateJobRequestRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createJobRequest(requestParameters: JobRequestBusinessApiCreateJobRequestRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateJobRequest200Response> {
            return localVarFp.createJobRequest(requestParameters.jobRequestCreateRequest, requestParameters.xTimezone, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a job request
         * @param {JobRequestBusinessApiGetJobRequestRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJobRequest(requestParameters: JobRequestBusinessApiGetJobRequestRequest, options?: RawAxiosRequestConfig): AxiosPromise<GetJobRequest200Response> {
            return localVarFp.getJobRequest(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Per-status events[] composed from workflow snapshot + scattered typed cols + action_audit. FE renders as the Job Timeline panel (completed step = filled check, current = outline ring, upcoming = empty). entered_at nil for upcoming steps + older jobs missing the typed-col backfill.
         * @summary Job timeline (business surface — also serves tech via BusinessAuth)
         * @param {JobRequestBusinessApiGetJobRequestTimelineRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJobRequestTimeline(requestParameters: JobRequestBusinessApiGetJobRequestTimelineRequest, options?: RawAxiosRequestConfig): AxiosPromise<GetJobRequestTimeline200Response> {
            return localVarFp.getJobRequestTimeline(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Booking availability (business actor)
         * @param {JobRequestBusinessApiListJobRequestBookingWindowsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listJobRequestBookingWindows(requestParameters: JobRequestBusinessApiListJobRequestBookingWindowsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ListJobRequestBookingWindows200Response> {
            return localVarFp.listJobRequestBookingWindows(requestParameters.xTimezone, requestParameters.from, requestParameters.to, options).then((request) => request(axios, basePath));
        },
        /**
         * Keep your own copy of bookings in sync WITHOUT re-listing everything: returns the job requests whose state changed (created, status transition, reschedule, soft-delete/archive) at or after the `since` cursor, ordered oldest-change-first (updated_at ASC).  How to use it: (1) On your first poll OMIT `since` — the server primes the cursor at \"now\", returns no items and a `next_since`. (2) Store `next_since` and pass it as `since` on the next poll. (3) Apply each returned item to your store by UPSERTING on `id` (the server re-scans a ~5s safety window, so the same job may appear again — never blindly append). (4) If `has_more` is true the page filled to `limit` and more changes are already waiting — poll again immediately; otherwise wait your normal interval (e.g. 5–15s).  This is NOT pagination — it is a time-keyed change feed. Use the paginated GET /job-requests for the initial bulk load, then this endpoint to stay live. Filters (status_keys, customer_id, …) narrow the feed to the slice you care about.
         * @summary Poll for new & changed job requests (sync feed)
         * @param {JobRequestBusinessApiListJobRequestChangesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listJobRequestChanges(requestParameters: JobRequestBusinessApiListJobRequestChangesRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<ListJobRequestChanges200Response> {
            return localVarFp.listJobRequestChanges(requestParameters.statusKeys, requestParameters.priority, requestParameters.customerId, requestParameters.technicianId, requestParameters.scheduledFrom, requestParameters.scheduledTo, requestParameters.since, requestParameters.limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List job requests
         * @param {JobRequestBusinessApiListJobRequestsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listJobRequests(requestParameters: JobRequestBusinessApiListJobRequestsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<ListJobRequests200Response> {
            return localVarFp.listJobRequests(requestParameters.statusKeys, requestParameters.status, requestParameters.customerId, requestParameters.technicianId, requestParameters.scheduledFrom, requestParameters.scheduledTo, requestParameters.q, requestParameters.sort, requestParameters.page, requestParameters.limit, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createJobRequest operation in JobRequestBusinessApi.
 * @export
 * @interface JobRequestBusinessApiCreateJobRequestRequest
 */
export interface JobRequestBusinessApiCreateJobRequestRequest {
    /**
     * Booking payload
     * @type {JobRequestCreateRequest}
     * @memberof JobRequestBusinessApiCreateJobRequest
     */
    readonly jobRequestCreateRequest: JobRequestCreateRequest

    /**
     * Customer IANA timezone
     * @type {string}
     * @memberof JobRequestBusinessApiCreateJobRequest
     */
    readonly xTimezone?: string
}

/**
 * Request parameters for getJobRequest operation in JobRequestBusinessApi.
 * @export
 * @interface JobRequestBusinessApiGetJobRequestRequest
 */
export interface JobRequestBusinessApiGetJobRequestRequest {
    /**
     * Job request ID (UUID or short_code)
     * @type {string}
     * @memberof JobRequestBusinessApiGetJobRequest
     */
    readonly id: string
}

/**
 * Request parameters for getJobRequestTimeline operation in JobRequestBusinessApi.
 * @export
 * @interface JobRequestBusinessApiGetJobRequestTimelineRequest
 */
export interface JobRequestBusinessApiGetJobRequestTimelineRequest {
    /**
     * Job request ID (UUID or short_code)
     * @type {string}
     * @memberof JobRequestBusinessApiGetJobRequestTimeline
     */
    readonly id: string
}

/**
 * Request parameters for listJobRequestBookingWindows operation in JobRequestBusinessApi.
 * @export
 * @interface JobRequestBusinessApiListJobRequestBookingWindowsRequest
 */
export interface JobRequestBusinessApiListJobRequestBookingWindowsRequest {
    /**
     * Customer IANA timezone
     * @type {string}
     * @memberof JobRequestBusinessApiListJobRequestBookingWindows
     */
    readonly xTimezone: string

    /**
     * Start YYYY-MM-DD
     * @type {string}
     * @memberof JobRequestBusinessApiListJobRequestBookingWindows
     */
    readonly from?: string

    /**
     * End YYYY-MM-DD
     * @type {string}
     * @memberof JobRequestBusinessApiListJobRequestBookingWindows
     */
    readonly to?: string
}

/**
 * Request parameters for listJobRequestChanges operation in JobRequestBusinessApi.
 * @export
 * @interface JobRequestBusinessApiListJobRequestChangesRequest
 */
export interface JobRequestBusinessApiListJobRequestChangesRequest {
    /**
     * Comma-separated status slugs — only surface changes to jobs in these statuses
     * @type {string}
     * @memberof JobRequestBusinessApiListJobRequestChanges
     */
    readonly statusKeys?: string

    /**
     * Priority filter (normal|emergency)
     * @type {string}
     * @memberof JobRequestBusinessApiListJobRequestChanges
     */
    readonly priority?: string

    /**
     * Only changes to this customer\&#39;s jobs (UUID)
     * @type {string}
     * @memberof JobRequestBusinessApiListJobRequestChanges
     */
    readonly customerId?: string

    /**
     * Only changes to jobs assigned to this technician (UUID)
     * @type {string}
     * @memberof JobRequestBusinessApiListJobRequestChanges
     */
    readonly technicianId?: string

    /**
     * Filter from (YYYY-MM-DD or RFC3339); range is [from, to)
     * @type {string}
     * @memberof JobRequestBusinessApiListJobRequestChanges
     */
    readonly scheduledFrom?: string

    /**
     * Filter to (YYYY-MM-DD or RFC3339), exclusive
     * @type {string}
     * @memberof JobRequestBusinessApiListJobRequestChanges
     */
    readonly scheduledTo?: string

    /**
     * RFC3339 cursor from the prior response\&#39;s next_since. OMIT on the first poll to prime the cursor at server-now.
     * @type {string}
     * @memberof JobRequestBusinessApiListJobRequestChanges
     */
    readonly since?: string

    /**
     * Max changes per poll (default 15, max 1000). If the page fills, has_more&#x3D;true.
     * @type {number}
     * @memberof JobRequestBusinessApiListJobRequestChanges
     */
    readonly limit?: number
}

/**
 * Request parameters for listJobRequests operation in JobRequestBusinessApi.
 * @export
 * @interface JobRequestBusinessApiListJobRequestsRequest
 */
export interface JobRequestBusinessApiListJobRequestsRequest {
    /**
     * Comma-separated status slugs
     * @type {string}
     * @memberof JobRequestBusinessApiListJobRequests
     */
    readonly statusKeys?: string

    /**
     * active (default) | archived | all
     * @type {string}
     * @memberof JobRequestBusinessApiListJobRequests
     */
    readonly status?: string

    /**
     * Customer UUID
     * @type {string}
     * @memberof JobRequestBusinessApiListJobRequests
     */
    readonly customerId?: string

    /**
     * Technician UUID
     * @type {string}
     * @memberof JobRequestBusinessApiListJobRequests
     */
    readonly technicianId?: string

    /**
     * Filter from (YYYY-MM-DD or RFC3339); range is [from, to)
     * @type {string}
     * @memberof JobRequestBusinessApiListJobRequests
     */
    readonly scheduledFrom?: string

    /**
     * Filter to (YYYY-MM-DD or RFC3339), exclusive
     * @type {string}
     * @memberof JobRequestBusinessApiListJobRequests
     */
    readonly scheduledTo?: string

    /**
     * Search short_code or description (case-insensitive, partial match)
     * @type {string}
     * @memberof JobRequestBusinessApiListJobRequests
     */
    readonly q?: string

    /**
     * Sort key
     * @type {string}
     * @memberof JobRequestBusinessApiListJobRequests
     */
    readonly sort?: string

    /**
     * Page number
     * @type {number}
     * @memberof JobRequestBusinessApiListJobRequests
     */
    readonly page?: number

    /**
     * Page size
     * @type {number}
     * @memberof JobRequestBusinessApiListJobRequests
     */
    readonly limit?: number
}

/**
 * JobRequestBusinessApi - object-oriented interface
 * @export
 * @class JobRequestBusinessApi
 * @extends {BaseAPI}
 */
export class JobRequestBusinessApi extends BaseAPI {
    /**
     * 
     * @summary Create a job request (business actor)
     * @param {JobRequestBusinessApiCreateJobRequestRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobRequestBusinessApi
     */
    public createJobRequest(requestParameters: JobRequestBusinessApiCreateJobRequestRequest, options?: RawAxiosRequestConfig) {
        return JobRequestBusinessApiFp(this.configuration).createJobRequest(requestParameters.jobRequestCreateRequest, requestParameters.xTimezone, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a job request
     * @param {JobRequestBusinessApiGetJobRequestRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobRequestBusinessApi
     */
    public getJobRequest(requestParameters: JobRequestBusinessApiGetJobRequestRequest, options?: RawAxiosRequestConfig) {
        return JobRequestBusinessApiFp(this.configuration).getJobRequest(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Per-status events[] composed from workflow snapshot + scattered typed cols + action_audit. FE renders as the Job Timeline panel (completed step = filled check, current = outline ring, upcoming = empty). entered_at nil for upcoming steps + older jobs missing the typed-col backfill.
     * @summary Job timeline (business surface — also serves tech via BusinessAuth)
     * @param {JobRequestBusinessApiGetJobRequestTimelineRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobRequestBusinessApi
     */
    public getJobRequestTimeline(requestParameters: JobRequestBusinessApiGetJobRequestTimelineRequest, options?: RawAxiosRequestConfig) {
        return JobRequestBusinessApiFp(this.configuration).getJobRequestTimeline(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Booking availability (business actor)
     * @param {JobRequestBusinessApiListJobRequestBookingWindowsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobRequestBusinessApi
     */
    public listJobRequestBookingWindows(requestParameters: JobRequestBusinessApiListJobRequestBookingWindowsRequest, options?: RawAxiosRequestConfig) {
        return JobRequestBusinessApiFp(this.configuration).listJobRequestBookingWindows(requestParameters.xTimezone, requestParameters.from, requestParameters.to, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Keep your own copy of bookings in sync WITHOUT re-listing everything: returns the job requests whose state changed (created, status transition, reschedule, soft-delete/archive) at or after the `since` cursor, ordered oldest-change-first (updated_at ASC).  How to use it: (1) On your first poll OMIT `since` — the server primes the cursor at \"now\", returns no items and a `next_since`. (2) Store `next_since` and pass it as `since` on the next poll. (3) Apply each returned item to your store by UPSERTING on `id` (the server re-scans a ~5s safety window, so the same job may appear again — never blindly append). (4) If `has_more` is true the page filled to `limit` and more changes are already waiting — poll again immediately; otherwise wait your normal interval (e.g. 5–15s).  This is NOT pagination — it is a time-keyed change feed. Use the paginated GET /job-requests for the initial bulk load, then this endpoint to stay live. Filters (status_keys, customer_id, …) narrow the feed to the slice you care about.
     * @summary Poll for new & changed job requests (sync feed)
     * @param {JobRequestBusinessApiListJobRequestChangesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobRequestBusinessApi
     */
    public listJobRequestChanges(requestParameters: JobRequestBusinessApiListJobRequestChangesRequest = {}, options?: RawAxiosRequestConfig) {
        return JobRequestBusinessApiFp(this.configuration).listJobRequestChanges(requestParameters.statusKeys, requestParameters.priority, requestParameters.customerId, requestParameters.technicianId, requestParameters.scheduledFrom, requestParameters.scheduledTo, requestParameters.since, requestParameters.limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List job requests
     * @param {JobRequestBusinessApiListJobRequestsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobRequestBusinessApi
     */
    public listJobRequests(requestParameters: JobRequestBusinessApiListJobRequestsRequest = {}, options?: RawAxiosRequestConfig) {
        return JobRequestBusinessApiFp(this.configuration).listJobRequests(requestParameters.statusKeys, requestParameters.status, requestParameters.customerId, requestParameters.technicianId, requestParameters.scheduledFrom, requestParameters.scheduledTo, requestParameters.q, requestParameters.sort, requestParameters.page, requestParameters.limit, options).then((request) => request(this.axios, this.basePath));
    }
}

