/* tslint:disable */
/* eslint-disable */
/**
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { GetJobType200Response } from '../models';
// @ts-ignore
import type { ListJobTypes200Response } from '../models';
// @ts-ignore
import type { ResponseEnvelope } from '../models';
/**
 * JobTypesApi - axios parameter creator
 * @export
 */
export const JobTypesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns one entry of the business\'s service catalog (job/work-order type) with its localized display name — e.g. an HVAC tune-up, drain cleaning or electrical inspection offering.
         * @summary Get a job type
         * @param {string} id Job Type ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJobType: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getJobType', 'id', id)
            const localVarPath = `/job-types/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the business\'s service catalog — the job/work-order types it offers (e.g. installation, repair, maintenance, inspection for trades like HVAC, plumbing, electrical, cleaning). Use it to discover the `job_type_id` accepted when booking a job request, or to render a services menu on your own site.
         * @summary List job types
         * @param {string} [status] Filter by status (active|inactive)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listJobTypes: async (status?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/job-types`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * JobTypesApi - functional programming interface
 * @export
 */
export const JobTypesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = JobTypesApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns one entry of the business\'s service catalog (job/work-order type) with its localized display name — e.g. an HVAC tune-up, drain cleaning or electrical inspection offering.
         * @summary Get a job type
         * @param {string} id Job Type ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getJobType(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetJobType200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getJobType(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JobTypesApi.getJobType']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns the business\'s service catalog — the job/work-order types it offers (e.g. installation, repair, maintenance, inspection for trades like HVAC, plumbing, electrical, cleaning). Use it to discover the `job_type_id` accepted when booking a job request, or to render a services menu on your own site.
         * @summary List job types
         * @param {string} [status] Filter by status (active|inactive)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listJobTypes(status?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListJobTypes200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listJobTypes(status, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JobTypesApi.listJobTypes']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * JobTypesApi - factory interface
 * @export
 */
export const JobTypesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = JobTypesApiFp(configuration)
    return {
        /**
         * Returns one entry of the business\'s service catalog (job/work-order type) with its localized display name — e.g. an HVAC tune-up, drain cleaning or electrical inspection offering.
         * @summary Get a job type
         * @param {JobTypesApiGetJobTypeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJobType(requestParameters: JobTypesApiGetJobTypeRequest, options?: RawAxiosRequestConfig): AxiosPromise<GetJobType200Response> {
            return localVarFp.getJobType(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the business\'s service catalog — the job/work-order types it offers (e.g. installation, repair, maintenance, inspection for trades like HVAC, plumbing, electrical, cleaning). Use it to discover the `job_type_id` accepted when booking a job request, or to render a services menu on your own site.
         * @summary List job types
         * @param {JobTypesApiListJobTypesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listJobTypes(requestParameters: JobTypesApiListJobTypesRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<ListJobTypes200Response> {
            return localVarFp.listJobTypes(requestParameters.status, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getJobType operation in JobTypesApi.
 * @export
 * @interface JobTypesApiGetJobTypeRequest
 */
export interface JobTypesApiGetJobTypeRequest {
    /**
     * Job Type ID
     * @type {string}
     * @memberof JobTypesApiGetJobType
     */
    readonly id: string
}

/**
 * Request parameters for listJobTypes operation in JobTypesApi.
 * @export
 * @interface JobTypesApiListJobTypesRequest
 */
export interface JobTypesApiListJobTypesRequest {
    /**
     * Filter by status (active|inactive)
     * @type {string}
     * @memberof JobTypesApiListJobTypes
     */
    readonly status?: string
}

/**
 * JobTypesApi - object-oriented interface
 * @export
 * @class JobTypesApi
 * @extends {BaseAPI}
 */
export class JobTypesApi extends BaseAPI {
    /**
     * Returns one entry of the business\'s service catalog (job/work-order type) with its localized display name — e.g. an HVAC tune-up, drain cleaning or electrical inspection offering.
     * @summary Get a job type
     * @param {JobTypesApiGetJobTypeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobTypesApi
     */
    public getJobType(requestParameters: JobTypesApiGetJobTypeRequest, options?: RawAxiosRequestConfig) {
        return JobTypesApiFp(this.configuration).getJobType(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns the business\'s service catalog — the job/work-order types it offers (e.g. installation, repair, maintenance, inspection for trades like HVAC, plumbing, electrical, cleaning). Use it to discover the `job_type_id` accepted when booking a job request, or to render a services menu on your own site.
     * @summary List job types
     * @param {JobTypesApiListJobTypesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobTypesApi
     */
    public listJobTypes(requestParameters: JobTypesApiListJobTypesRequest = {}, options?: RawAxiosRequestConfig) {
        return JobTypesApiFp(this.configuration).listJobTypes(requestParameters.status, options).then((request) => request(this.axios, this.basePath));
    }
}

