/* tslint:disable */
/* eslint-disable */
/**
 * CrispHive Developer API
 * Public REST API for integrating CrispHive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { GetServiceArea200Response } from '../models';
// @ts-ignore
import type { ListServiceAreas200Response } from '../models';
// @ts-ignore
import type { ResponseEnvelope } from '../models';
/**
 * ServiceAreaApi - axios parameter creator
 * @export
 */
export const ServiceAreaApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns details of a specific service area
         * @summary Get a service area
         * @param {string} id Service Area ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getServiceArea: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getServiceArea', 'id', id)
            const localVarPath = `/service-areas/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a paginated list of service areas for the business
         * @summary List service areas
         * @param {number} [page] Page number (default 1)
         * @param {number} [limit] Items per page (default 15, max 1000)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listServiceAreas: async (page?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/service-areas`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ServiceAreaApi - functional programming interface
 * @export
 */
export const ServiceAreaApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ServiceAreaApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns details of a specific service area
         * @summary Get a service area
         * @param {string} id Service Area ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getServiceArea(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetServiceArea200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getServiceArea(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ServiceAreaApi.getServiceArea']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns a paginated list of service areas for the business
         * @summary List service areas
         * @param {number} [page] Page number (default 1)
         * @param {number} [limit] Items per page (default 15, max 1000)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listServiceAreas(page?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListServiceAreas200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listServiceAreas(page, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ServiceAreaApi.listServiceAreas']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ServiceAreaApi - factory interface
 * @export
 */
export const ServiceAreaApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ServiceAreaApiFp(configuration)
    return {
        /**
         * Returns details of a specific service area
         * @summary Get a service area
         * @param {ServiceAreaApiGetServiceAreaRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getServiceArea(requestParameters: ServiceAreaApiGetServiceAreaRequest, options?: RawAxiosRequestConfig): AxiosPromise<GetServiceArea200Response> {
            return localVarFp.getServiceArea(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a paginated list of service areas for the business
         * @summary List service areas
         * @param {ServiceAreaApiListServiceAreasRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listServiceAreas(requestParameters: ServiceAreaApiListServiceAreasRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<ListServiceAreas200Response> {
            return localVarFp.listServiceAreas(requestParameters.page, requestParameters.limit, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getServiceArea operation in ServiceAreaApi.
 * @export
 * @interface ServiceAreaApiGetServiceAreaRequest
 */
export interface ServiceAreaApiGetServiceAreaRequest {
    /**
     * Service Area ID
     * @type {string}
     * @memberof ServiceAreaApiGetServiceArea
     */
    readonly id: string
}

/**
 * Request parameters for listServiceAreas operation in ServiceAreaApi.
 * @export
 * @interface ServiceAreaApiListServiceAreasRequest
 */
export interface ServiceAreaApiListServiceAreasRequest {
    /**
     * Page number (default 1)
     * @type {number}
     * @memberof ServiceAreaApiListServiceAreas
     */
    readonly page?: number

    /**
     * Items per page (default 15, max 1000)
     * @type {number}
     * @memberof ServiceAreaApiListServiceAreas
     */
    readonly limit?: number
}

/**
 * ServiceAreaApi - object-oriented interface
 * @export
 * @class ServiceAreaApi
 * @extends {BaseAPI}
 */
export class ServiceAreaApi extends BaseAPI {
    /**
     * Returns details of a specific service area
     * @summary Get a service area
     * @param {ServiceAreaApiGetServiceAreaRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServiceAreaApi
     */
    public getServiceArea(requestParameters: ServiceAreaApiGetServiceAreaRequest, options?: RawAxiosRequestConfig) {
        return ServiceAreaApiFp(this.configuration).getServiceArea(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a paginated list of service areas for the business
     * @summary List service areas
     * @param {ServiceAreaApiListServiceAreasRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServiceAreaApi
     */
    public listServiceAreas(requestParameters: ServiceAreaApiListServiceAreasRequest = {}, options?: RawAxiosRequestConfig) {
        return ServiceAreaApiFp(this.configuration).listServiceAreas(requestParameters.page, requestParameters.limit, options).then((request) => request(this.axios, this.basePath));
    }
}

