/* tslint:disable */
/* eslint-disable */
/**
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateTechnicianTimeOff200Response } from '../models';
// @ts-ignore
import type { ListTechnicianTimeOff200Response } from '../models';
// @ts-ignore
import type { ResponseEnvelope } from '../models';
// @ts-ignore
import type { TechnicianTimeOffCreateRequest } from '../models';
/**
 * TechnicianTimeOffApi - axios parameter creator
 * @export
 */
export const TechnicianTimeOffApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Records a time-off block for a technician. The record is created PENDING; a business staff member approves it on the dashboard — EXCEPT for the sick-call flow, where `commitAbsenceResolve` approves the pending record that covers the absence itself. `start_datetime`/`end_datetime` are RFC3339 INSTANTS with an offset (e.g. `2030-06-15T04:00:00Z` for midnight Toronto), unlike the business-local naive datetimes used by scheduling calls — a whole day off is that day\'s local midnight to the next in UTC. Overlapping an existing record for the same technician is refused (`TIME_OFF_OVERLAP`); list `GET /technicians/{id}/time-off` first. Creating a record immediately flags the technician\'s jobs in that window as needing attention on the dispatch board. Supports Idempotency-Key.
         * @summary Record a technician\'s time off (sick day, leave)
         * @param {TechnicianTimeOffCreateRequest} technicianTimeOffCreateRequest Time off details
         * @param {string} [idempotencyKey] Unique key making retries safe: a repeat send with the same key replays the original response (header Idempotent-Replayed: true) instead of re-running the operation. Reusing a key with a different body returns 422 IDEMPOTENCY_KEY_REUSE.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTechnicianTimeOff: async (technicianTimeOffCreateRequest: TechnicianTimeOffCreateRequest, idempotencyKey?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'technicianTimeOffCreateRequest' is not null or undefined
            assertParamExists('createTechnicianTimeOff', 'technicianTimeOffCreateRequest', technicianTimeOffCreateRequest)
            const localVarPath = `/technician-time-off`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (idempotencyKey != null) {
                localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(technicianTimeOffCreateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the technician\'s time-off records (pending, approved, rejected, cancelled), paginated, optionally bounded by start_date/end_date (YYYY-MM-DD, inclusive overlap) and status. Read this before recording a new block (overlaps are refused) and to see whether an absence is already recorded before `commitAbsenceResolve`.
         * @summary List time off for a specific technician
         * @param {string} id Technician ID
         * @param {number} [page] Page number (default 1)
         * @param {number} [limit] Items per page (default 15)
         * @param {string} [startDate] Filter by start date (YYYY-MM-DD)
         * @param {string} [endDate] Filter by end date (YYYY-MM-DD)
         * @param {Array<string>} [statusIds] Filter by status (multi: pending|approved|rejected|cancelled)
         * @param {string} [keyword] Search reason (case-insensitive substring)
         * @param {string} [since] RFC3339 cursor for short-polling; echo back next_since from prior response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTechnicianTimeOff: async (id: string, page?: number, limit?: number, startDate?: string, endDate?: string, statusIds?: Array<string>, keyword?: string, since?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('listTechnicianTimeOff', 'id', id)
            const localVarPath = `/technicians/{id}/time-off`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (startDate !== undefined) {
                localVarQueryParameter['start_date'] = startDate;
            }

            if (endDate !== undefined) {
                localVarQueryParameter['end_date'] = endDate;
            }

            if (statusIds) {
                localVarQueryParameter['status_ids'] = statusIds;
            }

            if (keyword !== undefined) {
                localVarQueryParameter['keyword'] = keyword;
            }

            if (since !== undefined) {
                localVarQueryParameter['since'] = since;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TechnicianTimeOffApi - functional programming interface
 * @export
 */
export const TechnicianTimeOffApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TechnicianTimeOffApiAxiosParamCreator(configuration)
    return {
        /**
         * Records a time-off block for a technician. The record is created PENDING; a business staff member approves it on the dashboard — EXCEPT for the sick-call flow, where `commitAbsenceResolve` approves the pending record that covers the absence itself. `start_datetime`/`end_datetime` are RFC3339 INSTANTS with an offset (e.g. `2030-06-15T04:00:00Z` for midnight Toronto), unlike the business-local naive datetimes used by scheduling calls — a whole day off is that day\'s local midnight to the next in UTC. Overlapping an existing record for the same technician is refused (`TIME_OFF_OVERLAP`); list `GET /technicians/{id}/time-off` first. Creating a record immediately flags the technician\'s jobs in that window as needing attention on the dispatch board. Supports Idempotency-Key.
         * @summary Record a technician\'s time off (sick day, leave)
         * @param {TechnicianTimeOffCreateRequest} technicianTimeOffCreateRequest Time off details
         * @param {string} [idempotencyKey] Unique key making retries safe: a repeat send with the same key replays the original response (header Idempotent-Replayed: true) instead of re-running the operation. Reusing a key with a different body returns 422 IDEMPOTENCY_KEY_REUSE.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createTechnicianTimeOff(technicianTimeOffCreateRequest: TechnicianTimeOffCreateRequest, idempotencyKey?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateTechnicianTimeOff200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createTechnicianTimeOff(technicianTimeOffCreateRequest, idempotencyKey, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TechnicianTimeOffApi.createTechnicianTimeOff']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns the technician\'s time-off records (pending, approved, rejected, cancelled), paginated, optionally bounded by start_date/end_date (YYYY-MM-DD, inclusive overlap) and status. Read this before recording a new block (overlaps are refused) and to see whether an absence is already recorded before `commitAbsenceResolve`.
         * @summary List time off for a specific technician
         * @param {string} id Technician ID
         * @param {number} [page] Page number (default 1)
         * @param {number} [limit] Items per page (default 15)
         * @param {string} [startDate] Filter by start date (YYYY-MM-DD)
         * @param {string} [endDate] Filter by end date (YYYY-MM-DD)
         * @param {Array<string>} [statusIds] Filter by status (multi: pending|approved|rejected|cancelled)
         * @param {string} [keyword] Search reason (case-insensitive substring)
         * @param {string} [since] RFC3339 cursor for short-polling; echo back next_since from prior response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listTechnicianTimeOff(id: string, page?: number, limit?: number, startDate?: string, endDate?: string, statusIds?: Array<string>, keyword?: string, since?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListTechnicianTimeOff200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listTechnicianTimeOff(id, page, limit, startDate, endDate, statusIds, keyword, since, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TechnicianTimeOffApi.listTechnicianTimeOff']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TechnicianTimeOffApi - factory interface
 * @export
 */
export const TechnicianTimeOffApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TechnicianTimeOffApiFp(configuration)
    return {
        /**
         * Records a time-off block for a technician. The record is created PENDING; a business staff member approves it on the dashboard — EXCEPT for the sick-call flow, where `commitAbsenceResolve` approves the pending record that covers the absence itself. `start_datetime`/`end_datetime` are RFC3339 INSTANTS with an offset (e.g. `2030-06-15T04:00:00Z` for midnight Toronto), unlike the business-local naive datetimes used by scheduling calls — a whole day off is that day\'s local midnight to the next in UTC. Overlapping an existing record for the same technician is refused (`TIME_OFF_OVERLAP`); list `GET /technicians/{id}/time-off` first. Creating a record immediately flags the technician\'s jobs in that window as needing attention on the dispatch board. Supports Idempotency-Key.
         * @summary Record a technician\'s time off (sick day, leave)
         * @param {TechnicianTimeOffApiCreateTechnicianTimeOffRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTechnicianTimeOff(requestParameters: TechnicianTimeOffApiCreateTechnicianTimeOffRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateTechnicianTimeOff200Response> {
            return localVarFp.createTechnicianTimeOff(requestParameters.technicianTimeOffCreateRequest, requestParameters.idempotencyKey, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the technician\'s time-off records (pending, approved, rejected, cancelled), paginated, optionally bounded by start_date/end_date (YYYY-MM-DD, inclusive overlap) and status. Read this before recording a new block (overlaps are refused) and to see whether an absence is already recorded before `commitAbsenceResolve`.
         * @summary List time off for a specific technician
         * @param {TechnicianTimeOffApiListTechnicianTimeOffRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTechnicianTimeOff(requestParameters: TechnicianTimeOffApiListTechnicianTimeOffRequest, options?: RawAxiosRequestConfig): AxiosPromise<ListTechnicianTimeOff200Response> {
            return localVarFp.listTechnicianTimeOff(requestParameters.id, requestParameters.page, requestParameters.limit, requestParameters.startDate, requestParameters.endDate, requestParameters.statusIds, requestParameters.keyword, requestParameters.since, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createTechnicianTimeOff operation in TechnicianTimeOffApi.
 * @export
 * @interface TechnicianTimeOffApiCreateTechnicianTimeOffRequest
 */
export interface TechnicianTimeOffApiCreateTechnicianTimeOffRequest {
    /**
     * Time off details
     * @type {TechnicianTimeOffCreateRequest}
     * @memberof TechnicianTimeOffApiCreateTechnicianTimeOff
     */
    readonly technicianTimeOffCreateRequest: TechnicianTimeOffCreateRequest

    /**
     * Unique key making retries safe: a repeat send with the same key replays the original response (header Idempotent-Replayed: true) instead of re-running the operation. Reusing a key with a different body returns 422 IDEMPOTENCY_KEY_REUSE.
     * @type {string}
     * @memberof TechnicianTimeOffApiCreateTechnicianTimeOff
     */
    readonly idempotencyKey?: string
}

/**
 * Request parameters for listTechnicianTimeOff operation in TechnicianTimeOffApi.
 * @export
 * @interface TechnicianTimeOffApiListTechnicianTimeOffRequest
 */
export interface TechnicianTimeOffApiListTechnicianTimeOffRequest {
    /**
     * Technician ID
     * @type {string}
     * @memberof TechnicianTimeOffApiListTechnicianTimeOff
     */
    readonly id: string

    /**
     * Page number (default 1)
     * @type {number}
     * @memberof TechnicianTimeOffApiListTechnicianTimeOff
     */
    readonly page?: number

    /**
     * Items per page (default 15)
     * @type {number}
     * @memberof TechnicianTimeOffApiListTechnicianTimeOff
     */
    readonly limit?: number

    /**
     * Filter by start date (YYYY-MM-DD)
     * @type {string}
     * @memberof TechnicianTimeOffApiListTechnicianTimeOff
     */
    readonly startDate?: string

    /**
     * Filter by end date (YYYY-MM-DD)
     * @type {string}
     * @memberof TechnicianTimeOffApiListTechnicianTimeOff
     */
    readonly endDate?: string

    /**
     * Filter by status (multi: pending|approved|rejected|cancelled)
     * @type {Array<string>}
     * @memberof TechnicianTimeOffApiListTechnicianTimeOff
     */
    readonly statusIds?: Array<string>

    /**
     * Search reason (case-insensitive substring)
     * @type {string}
     * @memberof TechnicianTimeOffApiListTechnicianTimeOff
     */
    readonly keyword?: string

    /**
     * RFC3339 cursor for short-polling; echo back next_since from prior response
     * @type {string}
     * @memberof TechnicianTimeOffApiListTechnicianTimeOff
     */
    readonly since?: string
}

/**
 * TechnicianTimeOffApi - object-oriented interface
 * @export
 * @class TechnicianTimeOffApi
 * @extends {BaseAPI}
 */
export class TechnicianTimeOffApi extends BaseAPI {
    /**
     * Records a time-off block for a technician. The record is created PENDING; a business staff member approves it on the dashboard — EXCEPT for the sick-call flow, where `commitAbsenceResolve` approves the pending record that covers the absence itself. `start_datetime`/`end_datetime` are RFC3339 INSTANTS with an offset (e.g. `2030-06-15T04:00:00Z` for midnight Toronto), unlike the business-local naive datetimes used by scheduling calls — a whole day off is that day\'s local midnight to the next in UTC. Overlapping an existing record for the same technician is refused (`TIME_OFF_OVERLAP`); list `GET /technicians/{id}/time-off` first. Creating a record immediately flags the technician\'s jobs in that window as needing attention on the dispatch board. Supports Idempotency-Key.
     * @summary Record a technician\'s time off (sick day, leave)
     * @param {TechnicianTimeOffApiCreateTechnicianTimeOffRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TechnicianTimeOffApi
     */
    public createTechnicianTimeOff(requestParameters: TechnicianTimeOffApiCreateTechnicianTimeOffRequest, options?: RawAxiosRequestConfig) {
        return TechnicianTimeOffApiFp(this.configuration).createTechnicianTimeOff(requestParameters.technicianTimeOffCreateRequest, requestParameters.idempotencyKey, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns the technician\'s time-off records (pending, approved, rejected, cancelled), paginated, optionally bounded by start_date/end_date (YYYY-MM-DD, inclusive overlap) and status. Read this before recording a new block (overlaps are refused) and to see whether an absence is already recorded before `commitAbsenceResolve`.
     * @summary List time off for a specific technician
     * @param {TechnicianTimeOffApiListTechnicianTimeOffRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TechnicianTimeOffApi
     */
    public listTechnicianTimeOff(requestParameters: TechnicianTimeOffApiListTechnicianTimeOffRequest, options?: RawAxiosRequestConfig) {
        return TechnicianTimeOffApiFp(this.configuration).listTechnicianTimeOff(requestParameters.id, requestParameters.page, requestParameters.limit, requestParameters.startDate, requestParameters.endDate, requestParameters.statusIds, requestParameters.keyword, requestParameters.since, options).then((request) => request(this.axios, this.basePath));
    }
}

