/* tslint:disable */
/* eslint-disable */
/**
 * CrispHive Developer API
 * Public REST API for integrating CrispHive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { GetVehicle200Response } from '../models';
// @ts-ignore
import type { ListVehicles200Response } from '../models';
// @ts-ignore
import type { ResponseEnvelope } from '../models';
/**
 * VehicleApi - axios parameter creator
 * @export
 */
export const VehicleApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns details of a specific vehicle
         * @summary Get a vehicle
         * @param {string} id Vehicle ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVehicle: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getVehicle', 'id', id)
            const localVarPath = `/vehicles/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a paginated list of vehicles for the business
         * @summary List vehicles
         * @param {number} [page] Page number (default 1)
         * @param {number} [limit] Items per page (default 15, max 1000)
         * @param {string} [status] Filter by status (inactive, idle, on_job, maintenance)
         * @param {string} [keyword] Search by name, brand, model, or plate number
         * @param {string} [since] RFC3339 cursor for short-polling; echo back next_since from prior response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listVehicles: async (page?: number, limit?: number, status?: string, keyword?: string, since?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/vehicles`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (keyword !== undefined) {
                localVarQueryParameter['keyword'] = keyword;
            }

            if (since !== undefined) {
                localVarQueryParameter['since'] = since;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * VehicleApi - functional programming interface
 * @export
 */
export const VehicleApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = VehicleApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns details of a specific vehicle
         * @summary Get a vehicle
         * @param {string} id Vehicle ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVehicle(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetVehicle200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getVehicle(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VehicleApi.getVehicle']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns a paginated list of vehicles for the business
         * @summary List vehicles
         * @param {number} [page] Page number (default 1)
         * @param {number} [limit] Items per page (default 15, max 1000)
         * @param {string} [status] Filter by status (inactive, idle, on_job, maintenance)
         * @param {string} [keyword] Search by name, brand, model, or plate number
         * @param {string} [since] RFC3339 cursor for short-polling; echo back next_since from prior response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listVehicles(page?: number, limit?: number, status?: string, keyword?: string, since?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListVehicles200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listVehicles(page, limit, status, keyword, since, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VehicleApi.listVehicles']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * VehicleApi - factory interface
 * @export
 */
export const VehicleApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = VehicleApiFp(configuration)
    return {
        /**
         * Returns details of a specific vehicle
         * @summary Get a vehicle
         * @param {VehicleApiGetVehicleRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVehicle(requestParameters: VehicleApiGetVehicleRequest, options?: RawAxiosRequestConfig): AxiosPromise<GetVehicle200Response> {
            return localVarFp.getVehicle(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a paginated list of vehicles for the business
         * @summary List vehicles
         * @param {VehicleApiListVehiclesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listVehicles(requestParameters: VehicleApiListVehiclesRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<ListVehicles200Response> {
            return localVarFp.listVehicles(requestParameters.page, requestParameters.limit, requestParameters.status, requestParameters.keyword, requestParameters.since, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getVehicle operation in VehicleApi.
 * @export
 * @interface VehicleApiGetVehicleRequest
 */
export interface VehicleApiGetVehicleRequest {
    /**
     * Vehicle ID
     * @type {string}
     * @memberof VehicleApiGetVehicle
     */
    readonly id: string
}

/**
 * Request parameters for listVehicles operation in VehicleApi.
 * @export
 * @interface VehicleApiListVehiclesRequest
 */
export interface VehicleApiListVehiclesRequest {
    /**
     * Page number (default 1)
     * @type {number}
     * @memberof VehicleApiListVehicles
     */
    readonly page?: number

    /**
     * Items per page (default 15, max 1000)
     * @type {number}
     * @memberof VehicleApiListVehicles
     */
    readonly limit?: number

    /**
     * Filter by status (inactive, idle, on_job, maintenance)
     * @type {string}
     * @memberof VehicleApiListVehicles
     */
    readonly status?: string

    /**
     * Search by name, brand, model, or plate number
     * @type {string}
     * @memberof VehicleApiListVehicles
     */
    readonly keyword?: string

    /**
     * RFC3339 cursor for short-polling; echo back next_since from prior response
     * @type {string}
     * @memberof VehicleApiListVehicles
     */
    readonly since?: string
}

/**
 * VehicleApi - object-oriented interface
 * @export
 * @class VehicleApi
 * @extends {BaseAPI}
 */
export class VehicleApi extends BaseAPI {
    /**
     * Returns details of a specific vehicle
     * @summary Get a vehicle
     * @param {VehicleApiGetVehicleRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VehicleApi
     */
    public getVehicle(requestParameters: VehicleApiGetVehicleRequest, options?: RawAxiosRequestConfig) {
        return VehicleApiFp(this.configuration).getVehicle(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a paginated list of vehicles for the business
     * @summary List vehicles
     * @param {VehicleApiListVehiclesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VehicleApi
     */
    public listVehicles(requestParameters: VehicleApiListVehiclesRequest = {}, options?: RawAxiosRequestConfig) {
        return VehicleApiFp(this.configuration).listVehicles(requestParameters.page, requestParameters.limit, requestParameters.status, requestParameters.keyword, requestParameters.since, options).then((request) => request(this.axios, this.basePath));
    }
}

