/* tslint:disable */
/* eslint-disable */
/**
 * CrispHive Developer API
 * Public REST API for integrating CrispHive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CustomerAddressRequest } from './customer-address-request';

/**
 * 
 * @export
 * @interface CustomerUpdateRequest
 */
export interface CustomerUpdateRequest {
    /**
     * Postal address and coordinates.
     * @type {CustomerAddressRequest}
     * @memberof CustomerUpdateRequest
     */
    'address'?: CustomerAddressRequest;
    /**
     * Email address.
     * @type {string}
     * @memberof CustomerUpdateRequest
     */
    'email'?: string;
    /**
     * Customer\'s full name. Required; max 255 chars.
     * @type {string}
     * @memberof CustomerUpdateRequest
     */
    'full_name': string;
    /**
     * Free-form internal notes about the customer; max 4000 chars.
     * @type {string}
     * @memberof CustomerUpdateRequest
     */
    'notes'?: string;
    /**
     * Phone number. 10–20 chars.
     * @type {string}
     * @memberof CustomerUpdateRequest
     */
    'phone'?: string;
    /**
     * UUID of the technician this customer prefers. Must belong to this business.
     * @type {string}
     * @memberof CustomerUpdateRequest
     */
    'preferred_technician_id'?: string;
    /**
     * UUID of the service area for this customer. Must belong to this business.
     * @type {string}
     * @memberof CustomerUpdateRequest
     */
    'service_area_id'?: string;
    /**
     * Lifecycle status.
     * @type {string}
     * @memberof CustomerUpdateRequest
     */
    'status'?: CustomerUpdateRequestStatusEnum;
    /**
     * Loyalty tier.
     * @type {string}
     * @memberof CustomerUpdateRequest
     */
    'tier'?: CustomerUpdateRequestTierEnum;
    /**
     * Your external reference for this customer. Optional; max 32 chars.
     * @type {string}
     * @memberof CustomerUpdateRequest
     */
    'uid'?: string;
}

export const CustomerUpdateRequestStatusEnum = {
    Active: 'active',
    Inactive: 'inactive'
} as const;

export type CustomerUpdateRequestStatusEnum = typeof CustomerUpdateRequestStatusEnum[keyof typeof CustomerUpdateRequestStatusEnum];
export const CustomerUpdateRequestTierEnum = {
    Regular: 'regular',
    Vip: 'vip'
} as const;

export type CustomerUpdateRequestTierEnum = typeof CustomerUpdateRequestTierEnum[keyof typeof CustomerUpdateRequestTierEnum];


