/* tslint:disable */
/* eslint-disable */
/**
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CustomerTierProgress } from './customer-tier-progress';

/**
 * 
 * @export
 * @interface CustomerSpending
 */
export interface CustomerSpending {
    /**
     * Average value per completed job.
     * @type {number}
     * @memberof CustomerSpending
     */
    'avg_job_value'?: number;
    /**
     * ISO 4217 currency code for the monetary fields (e.g. \"USD\", \"CAD\").
     * @type {string}
     * @memberof CustomerSpending
     */
    'currency'?: string;
    /**
     * Human-readable rank label (e.g. \"Top 5%\").
     * @type {string}
     * @memberof CustomerSpending
     */
    'rank_position_label'?: string;
    /**
     * Loyalty tier the spend resolves to.
     * @type {string}
     * @memberof CustomerSpending
     */
    'tier'?: CustomerSpendingTierEnum;
    /**
     * Progress toward the next tier.
     * @type {CustomerTierProgress}
     * @memberof CustomerSpending
     */
    'tier_progress'?: CustomerTierProgress;
    /**
     * Total amount spent in the trailing 12 months.
     * @type {number}
     * @memberof CustomerSpending
     */
    'total_spent_12m'?: number;
}

export const CustomerSpendingTierEnum = {
    Regular: 'regular',
    Vip: 'vip'
} as const;

export type CustomerSpendingTierEnum = typeof CustomerSpendingTierEnum[keyof typeof CustomerSpendingTierEnum];


