/* tslint:disable */
/* eslint-disable */
/**
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CustomerAddressRequest } from './customer-address-request';

/**
 * 
 * @export
 * @interface CustomerCreateRequest
 */
export interface CustomerCreateRequest {
    /**
     * Postal address and coordinates.
     * @type {CustomerAddressRequest}
     * @memberof CustomerCreateRequest
     */
    'address'?: CustomerAddressRequest;
    /**
     * Email address. Optional, but at least one of phone/email is required.
     * @type {string}
     * @memberof CustomerCreateRequest
     */
    'email'?: string;
    /**
     * Customer\'s full name. Required; max 255 chars.
     * @type {string}
     * @memberof CustomerCreateRequest
     */
    'full_name': string;
    /**
     * Phone number in E.164 international format: a leading `+` and the country code, e.g. `+16135550188`. A bare national number (`6135550188`) is REJECTED with PHONE_INVALID — there is no default region to guess the country from. Separators (spaces, dashes, parentheses) are stripped before validation. Optional, but at least one of phone/email is required; 10–20 chars.
     * @type {string}
     * @memberof CustomerCreateRequest
     */
    'phone'?: string;
    /**
     * UUID of the technician this customer prefers. Must belong to this business.
     * @type {string}
     * @memberof CustomerCreateRequest
     */
    'preferred_technician_id'?: string;
    /**
     * UUID of the service area for this customer. Must belong to this business.
     * @type {string}
     * @memberof CustomerCreateRequest
     */
    'service_area_id'?: string;
    /**
     * SMS consent: set true ONLY when the customer explicitly agreed to receive SMS (e.g. ticked a non-pre-checked consent box, or gave verbal/written consent you keep a record of). SMS notifications are suppressed while false.
     * @type {boolean}
     * @memberof CustomerCreateRequest
     */
    'sms_opt_in'?: boolean;
    /**
     * Loyalty tier. Defaults to \"regular\" if omitted.
     * @type {string}
     * @memberof CustomerCreateRequest
     */
    'tier'?: CustomerCreateRequestTierEnum;
    /**
     * Your external reference for this customer (your own system\'s ID). Optional; max 32 chars.
     * @type {string}
     * @memberof CustomerCreateRequest
     */
    'uid'?: string;
}

export const CustomerCreateRequestTierEnum = {
    Regular: 'regular',
    Vip: 'vip'
} as const;

export type CustomerCreateRequestTierEnum = typeof CustomerCreateRequestTierEnum[keyof typeof CustomerCreateRequestTierEnum];


