/* tslint:disable */
/* eslint-disable */
/**
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CustomerAddress } from './customer-address';
// May contain unused imports in some cases
// @ts-ignore
import type { CustomerServiceAreaRef } from './customer-service-area-ref';
// May contain unused imports in some cases
// @ts-ignore
import type { CustomerTechnicianRef } from './customer-technician-ref';

/**
 * 
 * @export
 * @interface CustomerContact
 */
export interface CustomerContact {
    /**
     * Postal address and coordinates.
     * @type {CustomerAddress}
     * @memberof CustomerContact
     */
    'address'?: CustomerAddress;
    /**
     * Email address.
     * @type {string}
     * @memberof CustomerContact
     */
    'email'?: string;
    /**
     * Phone number in the form it was supplied.
     * @type {string}
     * @memberof CustomerContact
     */
    'phone'?: string;
    /**
     * The technician this customer prefers, if one is set; otherwise null.
     * @type {CustomerTechnicianRef}
     * @memberof CustomerContact
     */
    'preferred_technician'?: CustomerTechnicianRef;
    /**
     * The service area this customer falls in, if resolved; otherwise null.
     * @type {CustomerServiceAreaRef}
     * @memberof CustomerContact
     */
    'service_area'?: CustomerServiceAreaRef;
    /**
     * True when the customer has explicitly consented to receive SMS. SMS notifications to this customer are suppressed while false.
     * @type {boolean}
     * @memberof CustomerContact
     */
    'sms_opt_in'?: boolean;
    /**
     * When SMS consent was granted (RFC3339); null when sms_opt_in is false.
     * @type {string}
     * @memberof CustomerContact
     */
    'sms_opt_in_at'?: string;
}

