/* tslint:disable */
/* eslint-disable */
/**
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CustomerProfile
 */
export interface CustomerProfile {
    /**
     * When the customer record was created (RFC3339).
     * @type {string}
     * @memberof CustomerProfile
     */
    'created_at'?: string;
    /**
     * Customer\'s full name.
     * @type {string}
     * @memberof CustomerProfile
     */
    'full_name'?: string;
    /**
     * Customer UUID — the stable identifier used in every customer endpoint.
     * @type {string}
     * @memberof CustomerProfile
     */
    'id'?: string;
    /**
     * Total number of job requests this customer has booked.
     * @type {number}
     * @memberof CustomerProfile
     */
    'request_count'?: number;
    /**
     * Lifecycle status.
     * @type {string}
     * @memberof CustomerProfile
     */
    'status'?: CustomerProfileStatusEnum;
    /**
     * Loyalty tier.
     * @type {string}
     * @memberof CustomerProfile
     */
    'tier'?: CustomerProfileTierEnum;
    /**
     * Your external reference for this customer (your own system\'s ID). Optional.
     * @type {string}
     * @memberof CustomerProfile
     */
    'uid'?: string;
}

export const CustomerProfileStatusEnum = {
    Active: 'active',
    Inactive: 'inactive'
} as const;

export type CustomerProfileStatusEnum = typeof CustomerProfileStatusEnum[keyof typeof CustomerProfileStatusEnum];
export const CustomerProfileTierEnum = {
    Regular: 'regular',
    Vip: 'vip'
} as const;

export type CustomerProfileTierEnum = typeof CustomerProfileTierEnum[keyof typeof CustomerProfileTierEnum];


