/* tslint:disable */
/* eslint-disable */
/**
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface JobRequestAbsenceTimeOff
 */
export interface JobRequestAbsenceTimeOff {
    /**
     * UUID of the time-off record covering the range.
     * @type {string}
     * @memberof JobRequestAbsenceTimeOff
     */
    'id'?: string;
    /**
     * Status after the commit — a pending record is approved by the commit.
     * @type {string}
     * @memberof JobRequestAbsenceTimeOff
     */
    'status_after'?: JobRequestAbsenceTimeOffStatusAfterEnum;
    /**
     * Status before the commit (pending | approved).
     * @type {string}
     * @memberof JobRequestAbsenceTimeOff
     */
    'status_before'?: JobRequestAbsenceTimeOffStatusBeforeEnum;
}

export const JobRequestAbsenceTimeOffStatusAfterEnum = {
    Pending: 'pending',
    Approved: 'approved'
} as const;

export type JobRequestAbsenceTimeOffStatusAfterEnum = typeof JobRequestAbsenceTimeOffStatusAfterEnum[keyof typeof JobRequestAbsenceTimeOffStatusAfterEnum];
export const JobRequestAbsenceTimeOffStatusBeforeEnum = {
    Pending: 'pending',
    Approved: 'approved'
} as const;

export type JobRequestAbsenceTimeOffStatusBeforeEnum = typeof JobRequestAbsenceTimeOffStatusBeforeEnum[keyof typeof JobRequestAbsenceTimeOffStatusBeforeEnum];


