/* tslint:disable */
/* eslint-disable */
/**
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface JobRequestMoveWarning
 */
export interface JobRequestMoveWarning {
    /**
     * Warning kind: TECH_NOT_FEASIBLE | PUSHED_OUTSIDE_WINDOW | OVERTIME | TIME_OFF_OVERLAP | VEHICLE_CONFLICT.
     * @type {string}
     * @memberof JobRequestMoveWarning
     */
    'code'?: JobRequestMoveWarningCodeEnum;
    /**
     * First same-day time the target technician CAN be on site (UTC) — only with reason=cannot_arrive_in_time; suggest it as the drop slot.
     * @type {string}
     * @memberof JobRequestMoveWarning
     */
    'earliest_feasible_at'?: string;
    /**
     * The displaced job this warning is about (per-job warnings only).
     * @type {string}
     * @memberof JobRequestMoveWarning
     */
    'job_id'?: string;
    /**
     * Human-readable explanation.
     * @type {string}
     * @memberof JobRequestMoveWarning
     */
    'message'?: string;
    /**
     * OVERTIME only: the largest overrun in minutes past the working-day end. Omitted otherwise.
     * @type {number}
     * @memberof JobRequestMoveWarning
     */
    'minutes'?: number;
    /**
     * Machine cause, TECH_NOT_FEASIBLE only: cannot_arrive_in_time (see earliest_feasible_at) | missing_required_skills | not_available_today | not_lead_tier.
     * @type {string}
     * @memberof JobRequestMoveWarning
     */
    'reason'?: JobRequestMoveWarningReasonEnum;
}

export const JobRequestMoveWarningCodeEnum = {
    TechNotFeasible: 'TECH_NOT_FEASIBLE',
    PushedOutsideWindow: 'PUSHED_OUTSIDE_WINDOW',
    Overtime: 'OVERTIME',
    TimeOffOverlap: 'TIME_OFF_OVERLAP',
    VehicleConflict: 'VEHICLE_CONFLICT'
} as const;

export type JobRequestMoveWarningCodeEnum = typeof JobRequestMoveWarningCodeEnum[keyof typeof JobRequestMoveWarningCodeEnum];
export const JobRequestMoveWarningReasonEnum = {
    CannotArriveInTime: 'cannot_arrive_in_time',
    MissingRequiredSkills: 'missing_required_skills',
    NotAvailableToday: 'not_available_today',
    NotLeadTier: 'not_lead_tier'
} as const;

export type JobRequestMoveWarningReasonEnum = typeof JobRequestMoveWarningReasonEnum[keyof typeof JobRequestMoveWarningReasonEnum];


