/* tslint:disable */
/* eslint-disable */
/**
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface JobRequestConfirmRequest
 */
export interface JobRequestConfirmRequest {
    /**
     * AfterHoursOverride (BUSINESS confirm only): schedule this P0 outside the technician\'s working hours or approved time-off — you have phoned them and they agreed. Requires priority p0, a single-person job, and technician_id. Double-booking, service area, required skills and the lead-tier rule still reject. Deliberately NOT a binding-tag rule: gin evaluates tags before the handler, which would make the three AFTER_HOURS codes unreachable.
     * @type {boolean}
     * @memberof JobRequestConfirmRequest
     */
    'after_hours_override'?: boolean;
    /**
     * ArrivalWindowMinutes = width (phút) của arrival-window ô khách bấm ở slot-picker (chính là time_slot_step_minutes, mặc định 30). Persist để post-confirm detail render lại đúng window. Optional; bounds ([5, 240], khớp slot-picker step) validate ở usecase — single authority, một error code (JOB_REQUEST_INVALID_INPUT).
     * @type {number}
     * @memberof JobRequestConfirmRequest
     */
    'arrival_window_minutes'?: number;
    /**
     * Chosen start time — business-local wall clock (the business_time.datetime value from the time-segments picker), converted to UTC against the job\'s business timezone. Seconds may be omitted and a space may replace the T. An offset is accepted only when it agrees with the business timezone; a disagreeing one is refused with JOB_REQUEST_INVALID_INPUT naming what it means locally.
     * @type {string}
     * @memberof JobRequestConfirmRequest
     */
    'scheduled_at'?: string;
    /**
     * Optimistic-lock fence: the status_version from your last read. Omitted/0 = fence on the row\'s current version (no race protection).
     * @type {number}
     * @memberof JobRequestConfirmRequest
     */
    'status_version'?: number;
    /**
     * TechnicianID (BUSINESS confirm only — ignored on the customer surface): force-assign the job to this technician instead of the ranked auto-pick. Ranking is bypassed; feasibility (hours/time-off/geo/skills), the TierLead rule and the double-booking guard still apply — an infeasible forced tech rejects the confirm (P0 gets the displacement hint).
     * @type {string}
     * @memberof JobRequestConfirmRequest
     */
    'technician_id'?: string;
}

