/* tslint:disable */
/* eslint-disable */
/**
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface JobRequestTimeSegmentsWorker
 */
export interface JobRequestTimeSegmentsWorker {
    /**
     * Estimated one-way distance from the technician\'s start location to the job site, in km (routing-provider estimate, straight-line fallback). 0 when unknown or on the pre-quote fallback path.
     * @type {number}
     * @memberof JobRequestTimeSegmentsWorker
     */
    'distance_km'?: number;
    /**
     * Distance sub-score (0-100; closer to the job = higher).
     * @type {number}
     * @memberof JobRequestTimeSegmentsWorker
     */
    'distance_score'?: number;
    /**
     * Technician\'s email; empty when not on file.
     * @type {string}
     * @memberof JobRequestTimeSegmentsWorker
     */
    'email'?: string;
    /**
     * Technician UUID.
     * @type {string}
     * @memberof JobRequestTimeSegmentsWorker
     */
    'id'?: string;
    /**
     * Minutes of job work already booked on this technician\'s schedule around the offered window (feeds the wrench-time score; lower = more open capacity).
     * @type {number}
     * @memberof JobRequestTimeSegmentsWorker
     */
    'job_duration_today_minutes'?: number;
    /**
     * Technician\'s full display name.
     * @type {string}
     * @memberof JobRequestTimeSegmentsWorker
     */
    'name'?: string;
    /**
     * Overall ranking score (0-100): weighted blend of the distance, travel-time, wrench-time and skill sub-scores; workers are listed best-first. Placeholder values on the pre-quote fallback path.
     * @type {number}
     * @memberof JobRequestTimeSegmentsWorker
     */
    'total_score'?: number;
    /**
     * Travel-time sub-score (0-100; shorter commute = higher).
     * @type {number}
     * @memberof JobRequestTimeSegmentsWorker
     */
    'travel_time_score'?: number;
    /**
     * Wrench-time sub-score (0-100; more open capacity vs the daily booked-work goal = higher).
     * @type {number}
     * @memberof JobRequestTimeSegmentsWorker
     */
    'wrench_time_score'?: number;
}

