/* tslint:disable */
/* eslint-disable */
/**
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface JobRequestRescheduleMove
 */
export interface JobRequestRescheduleMove {
    /**
     * Name of the displaced job\'s customer.
     * @type {string}
     * @memberof JobRequestRescheduleMove
     */
    'customer_name'?: string;
    /**
     * Current window end (UTC).
     * @type {string}
     * @memberof JobRequestRescheduleMove
     */
    'from_end'?: string;
    /**
     * Current window start (UTC) — where the job sits today.
     * @type {string}
     * @memberof JobRequestRescheduleMove
     */
    'from_start'?: string;
    /**
     * UUID of the displaced job.
     * @type {string}
     * @memberof JobRequestRescheduleMove
     */
    'job_id'?: string;
    /**
     * Priority of the displaced job (p0..p3) — what the coordinator is pushing.
     * @type {string}
     * @memberof JobRequestRescheduleMove
     */
    'priority'?: JobRequestRescheduleMovePriorityEnum;
    /**
     * Human-friendly short code of the displaced job.
     * @type {string}
     * @memberof JobRequestRescheduleMove
     */
    'short_code'?: string;
    /**
     * Proposed window end (UTC).
     * @type {string}
     * @memberof JobRequestRescheduleMove
     */
    'to_end'?: string;
    /**
     * Proposed window start (UTC) — where the job lands after the cascade.
     * @type {string}
     * @memberof JobRequestRescheduleMove
     */
    'to_start'?: string;
}

export const JobRequestRescheduleMovePriorityEnum = {
    P0: 'p0',
    P1: 'p1',
    P2: 'p2',
    P3: 'p3'
} as const;

export type JobRequestRescheduleMovePriorityEnum = typeof JobRequestRescheduleMovePriorityEnum[keyof typeof JobRequestRescheduleMovePriorityEnum];


