/* tslint:disable */
/* eslint-disable */
/**
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { JobRequestSession } from './job-request-session';
// May contain unused imports in some cases
// @ts-ignore
import type { JobRequestTimeSegmentsBusinessTime } from './job-request-time-segments-business-time';
// May contain unused imports in some cases
// @ts-ignore
import type { JobRequestTimeSegmentsWorker } from './job-request-time-segments-worker';

/**
 * 
 * @export
 * @interface JobRequestTimeSegmentsSlot
 */
export interface JobRequestTimeSegmentsSlot {
    /**
     * Technicians feasible for this slot, engine-ranked best first, each with its score breakdown.
     * @type {Array<JobRequestTimeSegmentsWorker>}
     * @memberof JobRequestTimeSegmentsSlot
     */
    'available_workers'?: Array<JobRequestTimeSegmentsWorker>;
    /**
     * True on the first slot of each day — the suggested \"BEST\" pick (UI hint).
     * @type {boolean}
     * @memberof JobRequestTimeSegmentsSlot
     */
    'best_time'?: boolean;
    /**
     * The same arrival window expressed in BUSINESS-local time; its naive datetime is the value to send back on confirm.
     * @type {JobRequestTimeSegmentsBusinessTime}
     * @memberof JobRequestTimeSegmentsSlot
     */
    'business_time'?: JobRequestTimeSegmentsBusinessTime;
    /**
     * Window start as an RFC3339 customer-local instant (with UTC offset).
     * @type {string}
     * @memberof JobRequestTimeSegmentsSlot
     */
    'datetime'?: string;
    /**
     * Span end (UTC) of a multi-day visit — render in business/customer timezone. Omitted for single-day slots.
     * @type {string}
     * @memberof JobRequestTimeSegmentsSlot
     */
    'ends_at'?: string;
    /**
     * MultiDay flags a slot whose visit cannot finish in one day and spans consecutive days. EndsAt + Sessions are then populated (for the best-ranked candidate — the one auto-assign would pick) so the picker can show the customer \"this start runs until <EndsAt>, over N days\" BEFORE they confirm. Single-day slots leave these empty (the slot itself is the visit).
     * @type {boolean}
     * @memberof JobRequestTimeSegmentsSlot
     */
    'multi_day'?: boolean;
    /**
     * Per-day session plan of a multi-day visit (for the best-ranked candidate). Omitted for single-day slots.
     * @type {Array<JobRequestSession>}
     * @memberof JobRequestTimeSegmentsSlot
     */
    'sessions'?: Array<JobRequestSession>;
    /**
     * Arrival-window start, HH:MM customer-local.
     * @type {string}
     * @memberof JobRequestTimeSegmentsSlot
     */
    'time'?: string;
    /**
     * Arrival-window end, HH:MM customer-local (= time + time_slot_step_minutes).
     * @type {string}
     * @memberof JobRequestTimeSegmentsSlot
     */
    'time_end'?: string;
    /**
     * Period bucket of the window start: 1=morning, 2=afternoon, 3=evening.
     * @type {number}
     * @memberof JobRequestTimeSegmentsSlot
     */
    'time_period'?: JobRequestTimeSegmentsSlotTimePeriodEnum;
    /**
     * Localized label for time_period.
     * @type {string}
     * @memberof JobRequestTimeSegmentsSlot
     */
    'time_period_label'?: JobRequestTimeSegmentsSlotTimePeriodLabelEnum;
    /**
     * Number of entries in available_workers.
     * @type {number}
     * @memberof JobRequestTimeSegmentsSlot
     */
    'workers_count'?: number;
}

export const JobRequestTimeSegmentsSlotTimePeriodEnum = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;

export type JobRequestTimeSegmentsSlotTimePeriodEnum = typeof JobRequestTimeSegmentsSlotTimePeriodEnum[keyof typeof JobRequestTimeSegmentsSlotTimePeriodEnum];
export const JobRequestTimeSegmentsSlotTimePeriodLabelEnum = {
    Morning: 'Morning',
    Afternoon: 'Afternoon',
    Evening: 'Evening'
} as const;

export type JobRequestTimeSegmentsSlotTimePeriodLabelEnum = typeof JobRequestTimeSegmentsSlotTimePeriodLabelEnum[keyof typeof JobRequestTimeSegmentsSlotTimePeriodLabelEnum];


