/* tslint:disable */
/* eslint-disable */
/**
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface JobRequestTimeSegmentsBusinessTime
 */
export interface JobRequestTimeSegmentsBusinessTime {
    /**
     * Calendar day of the window start, business-local (YYYY-MM-DD).
     * @type {string}
     * @memberof JobRequestTimeSegmentsBusinessTime
     */
    'date'?: string;
    /**
     * Window start as a naive business-local datetime (no UTC offset) — the exact value to send back as scheduled_at on confirm.
     * @type {string}
     * @memberof JobRequestTimeSegmentsBusinessTime
     */
    'datetime'?: string;
    /**
     * Full weekday name of the window start, business-local.
     * @type {string}
     * @memberof JobRequestTimeSegmentsBusinessTime
     */
    'day_name'?: string;
    /**
     * Arrival-window start, HH:MM business-local.
     * @type {string}
     * @memberof JobRequestTimeSegmentsBusinessTime
     */
    'time'?: string;
    /**
     * Arrival-window end, HH:MM business-local.
     * @type {string}
     * @memberof JobRequestTimeSegmentsBusinessTime
     */
    'time_end'?: string;
    /**
     * Period bucket of the window start, business-local: 1=morning, 2=afternoon, 3=evening.
     * @type {number}
     * @memberof JobRequestTimeSegmentsBusinessTime
     */
    'time_period'?: JobRequestTimeSegmentsBusinessTimeTimePeriodEnum;
    /**
     * Localized label for time_period.
     * @type {string}
     * @memberof JobRequestTimeSegmentsBusinessTime
     */
    'time_period_label'?: JobRequestTimeSegmentsBusinessTimeTimePeriodLabelEnum;
}

export const JobRequestTimeSegmentsBusinessTimeTimePeriodEnum = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;

export type JobRequestTimeSegmentsBusinessTimeTimePeriodEnum = typeof JobRequestTimeSegmentsBusinessTimeTimePeriodEnum[keyof typeof JobRequestTimeSegmentsBusinessTimeTimePeriodEnum];
export const JobRequestTimeSegmentsBusinessTimeTimePeriodLabelEnum = {
    Morning: 'Morning',
    Afternoon: 'Afternoon',
    Evening: 'Evening'
} as const;

export type JobRequestTimeSegmentsBusinessTimeTimePeriodLabelEnum = typeof JobRequestTimeSegmentsBusinessTimeTimePeriodLabelEnum[keyof typeof JobRequestTimeSegmentsBusinessTimeTimePeriodLabelEnum];


