/* tslint:disable */
/* eslint-disable */
/**
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface JobRequestAbsenceAlternativeCost
 */
export interface JobRequestAbsenceAlternativeCost {
    /**
     * The customer is told a NEW appointment time (job_rescheduled), not only a new technician name.
     * @type {boolean}
     * @memberof JobRequestAbsenceAlternativeCost
     */
    'customer_renotified'?: boolean;
    /**
     * Calendar days between the original and the new window\'s business-local dates (0 = same day / reassign).
     * @type {number}
     * @memberof JobRequestAbsenceAlternativeCost
     */
    'day_offset'?: number;
    /**
     * The technician\'s own driving distance to the site in km. ABSENT when the engine had no route — never render \"0 km\".
     * @type {number}
     * @memberof JobRequestAbsenceAlternativeCost
     */
    'distance_km'?: number;
    /**
     * The technician is not assigned to any service area covering the job (sent out of zone).
     * @type {boolean}
     * @memberof JobRequestAbsenceAlternativeCost
     */
    'outside_service_area'?: boolean;
    /**
     * The job carries an SLA deadline and the new window ends after it.
     * @type {boolean}
     * @memberof JobRequestAbsenceAlternativeCost
     */
    'sla_breached'?: boolean;
    /**
     * The technician\'s one-way commute estimate in minutes (rounded up). Absent when unknown.
     * @type {number}
     * @memberof JobRequestAbsenceAlternativeCost
     */
    'travel_minutes'?: number;
    /**
     * The customer\'s appointment changes (reschedule kinds).
     * @type {boolean}
     * @memberof JobRequestAbsenceAlternativeCost
     */
    'window_moved'?: boolean;
}

