/* tslint:disable */
/* eslint-disable */
/**
 * CrispHive Developer API
 * Public REST API for integrating CrispHive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface JobRequestSession
 */
export interface JobRequestSession {
    /**
     * Calendar day (YYYY-MM-DD) this session falls on, business-local.
     * @type {string}
     * @memberof JobRequestSession
     */
    'date'?: string;
    /**
     * DepartAt / ReturnAt bracket the technician\'s whole day (leave home / arrive home), derived from travel. Omitted together when travel is unknown.
     * @type {string}
     * @memberof JobRequestSession
     */
    'depart_at'?: string;
    /**
     * On-site end of this day\'s work block (UTC).
     * @type {string}
     * @memberof JobRequestSession
     */
    'end_at'?: string;
    /**
     * 1-based day index within the job\'s span (1 for single-day jobs).
     * @type {number}
     * @memberof JobRequestSession
     */
    'ordinal'?: number;
    /**
     * 
     * @type {string}
     * @memberof JobRequestSession
     */
    'return_at'?: string;
    /**
     * On-site start of this day\'s work block (UTC).
     * @type {string}
     * @memberof JobRequestSession
     */
    'start_at'?: string;
    /**
     * TravelMinutes is the planned one-way commute for this day. Omitted when unknown (admin-fallback job without geocoded location, or legacy row).
     * @type {number}
     * @memberof JobRequestSession
     */
    'travel_minutes'?: number;
}

