/* tslint:disable */
/* eslint-disable */
/**
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { JobRequestMoveWarning } from './job-request-move-warning';
// May contain unused imports in some cases
// @ts-ignore
import type { JobRequestRescheduleDay } from './job-request-reschedule-day';

/**
 * 
 * @export
 * @interface JobRequestEmergencyCandidate
 */
export interface JobRequestEmergencyCandidate {
    /**
     * Minutes of work already booked on this technician that day (workload context).
     * @type {number}
     * @memberof JobRequestEmergencyCandidate
     */
    'booked_minutes'?: number;
    /**
     * The displaced jobs, grouped per business-local day (same shape as the preview endpoint) — what the coordinator reviews before committing.
     * @type {Array<JobRequestRescheduleDay>}
     * @memberof JobRequestEmergencyCandidate
     */
    'days'?: Array<JobRequestRescheduleDay>;
    /**
     * Estimated distance from the tech\'s start location to the site, in kilometers.
     * @type {number}
     * @memberof JobRequestEmergencyCandidate
     */
    'distance_km'?: number;
    /**
     * Candidate technician\'s full name.
     * @type {string}
     * @memberof JobRequestEmergencyCandidate
     */
    'full_name'?: string;
    /**
     * Number of the job\'s desired skills this technician matches.
     * @type {number}
     * @memberof JobRequestEmergencyCandidate
     */
    'matched_skills'?: number;
    /**
     * UUID of the candidate technician.
     * @type {string}
     * @memberof JobRequestEmergencyCandidate
     */
    'technician_id'?: string;
    /**
     * How many jobs choosing this tech would push (0 = free slot).
     * @type {number}
     * @memberof JobRequestEmergencyCandidate
     */
    'total_moves'?: number;
    /**
     * Smart-assign engine ranking score (higher = better fit).
     * @type {number}
     * @memberof JobRequestEmergencyCandidate
     */
    'total_score'?: number;
    /**
     * ETA estimate in minutes from the tech\'s start location to the site — static origin (no live GPS), rank hint not a promise.
     * @type {number}
     * @memberof JobRequestEmergencyCandidate
     */
    'travel_minutes'?: number;
    /**
     * Per-technician warnings, e.g. TIME_OFF_OVERLAP when this technician is on approved leave at the requested time (only reachable with after_hours_override, which stops leave from rejecting).
     * @type {Array<JobRequestMoveWarning>}
     * @memberof JobRequestEmergencyCandidate
     */
    'warnings'?: Array<JobRequestMoveWarning>;
}

