/* tslint:disable */
/* eslint-disable */
/**
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface JobRequestCrewRecommendation
 */
export interface JobRequestCrewRecommendation {
    /**
     * Average recorded actual duration (minutes) across the sample; 0 when unrecorded.
     * @type {number}
     * @memberof JobRequestCrewRecommendation
     */
    'avg_actual_minutes'?: number;
    /**
     * Human-readable disclaimer — MUST be displayed next to the number (AC-2).
     * @type {string}
     * @memberof JobRequestCrewRecommendation
     */
    'disclaimer'?: string;
    /**
     * Largest crew observed in the sample.
     * @type {number}
     * @memberof JobRequestCrewRecommendation
     */
    'max_observed'?: number;
    /**
     * Suggested number of technicians (median of comparable completed jobs; 1 when no history).
     * @type {number}
     * @memberof JobRequestCrewRecommendation
     */
    'recommended_size'?: number;
    /**
     * How many completed jobs the suggestion is based on. 0 = no history.
     * @type {number}
     * @memberof JobRequestCrewRecommendation
     */
    'sample_size'?: number;
}

