/* tslint:disable */
/* eslint-disable */
/**
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { JobRequestCrewRecommendation } from './job-request-crew-recommendation';
// May contain unused imports in some cases
// @ts-ignore
import type { JobRequestEmergencyCandidate } from './job-request-emergency-candidate';

/**
 * 
 * @export
 * @interface JobRequestEmergencyCandidates
 */
export interface JobRequestEmergencyCandidates {
    /**
     * IANA timezone the per-day groupings are rendered in.
     * @type {string}
     * @memberof JobRequestEmergencyCandidates
     */
    'business_timezone'?: string;
    /**
     * Technicians ranked fastest-arrival first; each carries its displacement preview.
     * @type {Array<JobRequestEmergencyCandidate>}
     * @memberof JobRequestEmergencyCandidates
     */
    'candidates'?: Array<JobRequestEmergencyCandidate>;
    /**
     * Historical crew-size suggestion (FR-1) — ALWAYS advisory; confirm or override before dispatch. sample_size=0 = no history, size defaults to 1.
     * @type {JobRequestCrewRecommendation}
     * @memberof JobRequestEmergencyCandidates
     */
    'crew_recommendation'?: JobRequestCrewRecommendation;
    /**
     * Emergency visit window end (UTC) — start + the quoted visit duration.
     * @type {string}
     * @memberof JobRequestEmergencyCandidates
     */
    'emergency_end'?: string;
    /**
     * ID of the P0 job being placed.
     * @type {string}
     * @memberof JobRequestEmergencyCandidates
     */
    'emergency_job_id'?: string;
    /**
     * Emergency visit window start (UTC).
     * @type {string}
     * @memberof JobRequestEmergencyCandidates
     */
    'emergency_start'?: string;
    /**
     * Reschedule mode the displacement previews assume (overtime | next_day).
     * @type {string}
     * @memberof JobRequestEmergencyCandidates
     */
    'mode'?: JobRequestEmergencyCandidatesModeEnum;
}

export const JobRequestEmergencyCandidatesModeEnum = {
    Overtime: 'overtime',
    NextDay: 'next_day'
} as const;

export type JobRequestEmergencyCandidatesModeEnum = typeof JobRequestEmergencyCandidatesModeEnum[keyof typeof JobRequestEmergencyCandidatesModeEnum];


