/* tslint:disable */
/* eslint-disable */
/**
 * CrispHive Developer API
 * Public REST API for integrating CrispHive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { JobRequestDayWindows } from './job-request-day-windows';

/**
 * 
 * @export
 * @interface JobRequestBookingWindows
 */
export interface JobRequestBookingWindows {
    /**
     * Business alias the windows were computed for.
     * @type {string}
     * @memberof JobRequestBookingWindows
     */
    'alias'?: string;
    /**
     * IANA timezone of the business (the business_view ranges).
     * @type {string}
     * @memberof JobRequestBookingWindows
     */
    'business_timezone'?: string;
    /**
     * IANA timezone the customer-facing dates/periods are expressed in.
     * @type {string}
     * @memberof JobRequestBookingWindows
     */
    'customer_timezone'?: string;
    /**
     * Per-day availability, ordered chronologically.
     * @type {Array<JobRequestDayWindows>}
     * @memberof JobRequestBookingWindows
     */
    'days'?: Array<JobRequestDayWindows>;
}

