/* tslint:disable */
/* eslint-disable */
/**
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { JobRequestAbsenceResolvedJob } from './job-request-absence-resolved-job';
// May contain unused imports in some cases
// @ts-ignore
import type { JobRequestAbsenceSolver } from './job-request-absence-solver';
// May contain unused imports in some cases
// @ts-ignore
import type { JobRequestAbsenceTimeOff } from './job-request-absence-time-off';
// May contain unused imports in some cases
// @ts-ignore
import type { JobRequestAbsenceUnresolvedJob } from './job-request-absence-unresolved-job';
// May contain unused imports in some cases
// @ts-ignore
import type { JobRequestMoveWarning } from './job-request-move-warning';

/**
 * 
 * @export
 * @interface JobRequestAbsencePlan
 */
export interface JobRequestAbsencePlan {
    /**
     * IANA timezone the calendar days are read in.
     * @type {string}
     * @memberof JobRequestAbsencePlan
     */
    'business_timezone'?: string;
    /**
     * First / last day of the absence (YYYY-MM-DD, business-local, inclusive).
     * @type {string}
     * @memberof JobRequestAbsencePlan
     */
    'date'?: string;
    /**
     * Jobs on the technician\'s board inside the range that the plan considered.
     * @type {number}
     * @memberof JobRequestAbsencePlan
     */
    'orphaned_count'?: number;
    /**
     * Jobs handed to an alternate at their unchanged window (empty array, never null).
     * @type {Array<JobRequestAbsenceResolvedJob>}
     * @memberof JobRequestAbsencePlan
     */
    'resolved'?: Array<JobRequestAbsenceResolvedJob>;
    /**
     * Planner metadata.
     * @type {JobRequestAbsenceSolver}
     * @memberof JobRequestAbsencePlan
     */
    'solver'?: JobRequestAbsenceSolver;
    /**
     * The absent technician.
     * @type {string}
     * @memberof JobRequestAbsencePlan
     */
    'technician_id'?: string;
    /**
     * Full name of the absent technician.
     * @type {string}
     * @memberof JobRequestAbsencePlan
     */
    'technician_name'?: string;
    /**
     * Commit only: every time-off record the commit relied on for coverage — a pending one CONTAINED in the range is approved by the commit; an approved one is reported as-is.
     * @type {Array<JobRequestAbsenceTimeOff>}
     * @memberof JobRequestAbsencePlan
     */
    'time_offs'?: Array<JobRequestAbsenceTimeOff>;
    /**
     * Jobs left for the coordinator, each with a reason (empty array, never null).
     * @type {Array<JobRequestAbsenceUnresolvedJob>}
     * @memberof JobRequestAbsencePlan
     */
    'unresolved'?: Array<JobRequestAbsenceUnresolvedJob>;
    /**
     * 
     * @type {string}
     * @memberof JobRequestAbsencePlan
     */
    'until_date'?: string;
    /**
     * Non-blocking consequences (same vocabulary as the move/emergency plans). Empty in v1.
     * @type {Array<JobRequestMoveWarning>}
     * @memberof JobRequestAbsencePlan
     */
    'warnings'?: Array<JobRequestMoveWarning>;
}

