/* tslint:disable */
/* eslint-disable */
/**
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { JobRequestAbsenceAlternative } from './job-request-absence-alternative';
// May contain unused imports in some cases
// @ts-ignore
import type { JobRequestBlocker } from './job-request-blocker';

/**
 * 
 * @export
 * @interface JobRequestAbsenceUnresolvedJob
 */
export interface JobRequestAbsenceUnresolvedJob {
    /**
     * Preview, NO_QUALIFIED_TECH_FREE only: the relaxation ladder\'s priced options, cheapest constraint first — the FE\'s default is the first entry. Always an array; empty when even the ladder found nothing (and on commit rows). Each is a PROPOSAL until copied into commit.
     * @type {Array<JobRequestAbsenceAlternative>}
     * @memberof JobRequestAbsenceUnresolvedJob
     */
    'alternatives'?: Array<JobRequestAbsenceAlternative>;
    /**
     * Engine diagnosis for the refused technicians (best-effort, may be absent).
     * @type {Array<JobRequestBlocker>}
     * @memberof JobRequestAbsenceUnresolvedJob
     */
    'blockers'?: Array<JobRequestBlocker>;
    /**
     * Customer name on the job.
     * @type {string}
     * @memberof JobRequestAbsenceUnresolvedJob
     */
    'customer_name'?: string;
    /**
     * Business-local calendar day (YYYY-MM-DD).
     * @type {string}
     * @memberof JobRequestAbsenceUnresolvedJob
     */
    'date'?: string;
    /**
     * 
     * @type {string}
     * @memberof JobRequestAbsenceUnresolvedJob
     */
    'end_at'?: string;
    /**
     * UUID of the job.
     * @type {string}
     * @memberof JobRequestAbsenceUnresolvedJob
     */
    'job_id'?: string;
    /**
     * Human-readable explanation (English).
     * @type {string}
     * @memberof JobRequestAbsenceUnresolvedJob
     */
    'message'?: string;
    /**
     * Priority (p0..p3).
     * @type {string}
     * @memberof JobRequestAbsenceUnresolvedJob
     */
    'priority'?: JobRequestAbsenceUnresolvedJobPriorityEnum;
    /**
     * Why it stayed unresolved. EXTEND-ONLY — carry a default branch. NOT_COMMITTED appears on commit only (a row the caller left out).
     * @type {string}
     * @memberof JobRequestAbsenceUnresolvedJob
     */
    'reason_code'?: JobRequestAbsenceUnresolvedJobReasonCodeEnum;
    /**
     * Human-friendly short code.
     * @type {string}
     * @memberof JobRequestAbsenceUnresolvedJob
     */
    'short_code'?: string;
    /**
     * The job\'s window (UTC) — unchanged, still on the absent technician.
     * @type {string}
     * @memberof JobRequestAbsenceUnresolvedJob
     */
    'start_at'?: string;
}

export const JobRequestAbsenceUnresolvedJobPriorityEnum = {
    P0: 'p0',
    P1: 'p1',
    P2: 'p2',
    P3: 'p3'
} as const;

export type JobRequestAbsenceUnresolvedJobPriorityEnum = typeof JobRequestAbsenceUnresolvedJobPriorityEnum[keyof typeof JobRequestAbsenceUnresolvedJobPriorityEnum];
export const JobRequestAbsenceUnresolvedJobReasonCodeEnum = {
    NoQualifiedTechFree: 'NO_QUALIFIED_TECH_FREE',
    CrewJobUnsupported: 'CREW_JOB_UNSUPPORTED',
    MultidayUnsupported: 'MULTIDAY_UNSUPPORTED',
    InProgress: 'IN_PROGRESS',
    NotReassignable: 'NOT_REASSIGNABLE',
    NotCommitted: 'NOT_COMMITTED'
} as const;

export type JobRequestAbsenceUnresolvedJobReasonCodeEnum = typeof JobRequestAbsenceUnresolvedJobReasonCodeEnum[keyof typeof JobRequestAbsenceUnresolvedJobReasonCodeEnum];


