/* tslint:disable */
/* eslint-disable */
/**
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { JobRequestAbsenceAlternativeCost } from './job-request-absence-alternative-cost';
// May contain unused imports in some cases
// @ts-ignore
import type { JobRequestAbsenceNotification } from './job-request-absence-notification';

/**
 * 
 * @export
 * @interface JobRequestAbsenceResolvedJob
 */
export interface JobRequestAbsenceResolvedJob {
    /**
     * Commit only, when the placement came from unresolved[].alternatives[]: the accepted kind. Absent for a strict placement. EXTEND-ONLY.
     * @type {string}
     * @memberof JobRequestAbsenceResolvedJob
     */
    'alternative_kind'?: JobRequestAbsenceResolvedJobAlternativeKindEnum;
    /**
     * Commit only: the job\'s \"needs attention\" flag was cleared in the same write.
     * @type {boolean}
     * @memberof JobRequestAbsenceResolvedJob
     */
    'attention_cleared'?: boolean;
    /**
     * Minutes the alternate already has booked that day (load).
     * @type {number}
     * @memberof JobRequestAbsenceResolvedJob
     */
    'booked_minutes'?: number;
    /**
     * Commit only, with alternative_kind: what the business paid for this placement.
     * @type {JobRequestAbsenceAlternativeCost}
     * @memberof JobRequestAbsenceResolvedJob
     */
    'cost'?: JobRequestAbsenceAlternativeCost;
    /**
     * Customer name on the job.
     * @type {string}
     * @memberof JobRequestAbsenceResolvedJob
     */
    'customer_name'?: string;
    /**
     * Business-local calendar day the window starts on (YYYY-MM-DD) — group a multi-day range on it.
     * @type {string}
     * @memberof JobRequestAbsenceResolvedJob
     */
    'date'?: string;
    /**
     * 
     * @type {number}
     * @memberof JobRequestAbsenceResolvedJob
     */
    'desired_skills'?: number;
    /**
     * Alternate\'s driving distance to the site in km. ABSENT when the engine had no route (no start location, no job coordinates, routing failure) — hide the chip rather than rendering \"0 km\".
     * @type {number}
     * @memberof JobRequestAbsenceResolvedJob
     */
    'distance_km'?: number;
    /**
     * Window end (UTC).
     * @type {string}
     * @memberof JobRequestAbsenceResolvedJob
     */
    'end_at'?: string;
    /**
     * How many alternates could have taken this job.
     * @type {number}
     * @memberof JobRequestAbsenceResolvedJob
     */
    'feasible_count'?: number;
    /**
     * UUID of the absent technician losing the job.
     * @type {string}
     * @memberof JobRequestAbsenceResolvedJob
     */
    'from_technician_id'?: string;
    /**
     * UUID of the re-staffed job.
     * @type {string}
     * @memberof JobRequestAbsenceResolvedJob
     */
    'job_id'?: string;
    /**
     * Desired skills the alternate holds / the job asks for.
     * @type {number}
     * @memberof JobRequestAbsenceResolvedJob
     */
    'matched_skills'?: number;
    /**
     * Commit only: what the customer-notification routing will do for this job.
     * @type {JobRequestAbsenceNotification}
     * @memberof JobRequestAbsenceResolvedJob
     */
    'notification'?: JobRequestAbsenceNotification;
    /**
     * 
     * @type {string}
     * @memberof JobRequestAbsenceResolvedJob
     */
    'original_end_at'?: string;
    /**
     * Commit only, when window_preserved is false: the window the job LEFT (UTC).
     * @type {string}
     * @memberof JobRequestAbsenceResolvedJob
     */
    'original_start_at'?: string;
    /**
     * Priority (p0..p3).
     * @type {string}
     * @memberof JobRequestAbsenceResolvedJob
     */
    'priority'?: JobRequestAbsenceResolvedJobPriorityEnum;
    /**
     * Human-friendly short code.
     * @type {string}
     * @memberof JobRequestAbsenceResolvedJob
     */
    'short_code'?: string;
    /**
     * Window start (UTC). For a strict or reassign_out_of_area placement it is byte-identical to the job\'s current window; for an accepted reschedule alternative (commit) it is the NEW window.
     * @type {string}
     * @memberof JobRequestAbsenceResolvedJob
     */
    'start_at'?: string;
    /**
     * status_version: at preview the current value (echo it on commit); on the COMMIT response the post-commit value (+1).
     * @type {number}
     * @memberof JobRequestAbsenceResolvedJob
     */
    'status_version'?: number;
    /**
     * Full name of the alternate. Omitted when unresolved.
     * @type {string}
     * @memberof JobRequestAbsenceResolvedJob
     */
    'to_name'?: string;
    /**
     * UUID of the alternate receiving the job.
     * @type {string}
     * @memberof JobRequestAbsenceResolvedJob
     */
    'to_technician_id'?: string;
    /**
     * Engine ranking score for this alternate on this job (0..1).
     * @type {number}
     * @memberof JobRequestAbsenceResolvedJob
     */
    'total_score'?: number;
    /**
     * Alternate\'s one-way commute estimate in minutes (rounded up). Absent when unknown.
     * @type {number}
     * @memberof JobRequestAbsenceResolvedJob
     */
    'travel_minutes'?: number;
    /**
     * True unless the coordinator accepted a reschedule alternative — then false, and original_start_at/original_end_at carry the window the job left.
     * @type {boolean}
     * @memberof JobRequestAbsenceResolvedJob
     */
    'window_preserved'?: boolean;
}

export const JobRequestAbsenceResolvedJobAlternativeKindEnum = {
    ReassignOutOfArea: 'reassign_out_of_area',
    RescheduleSameDay: 'reschedule_same_day',
    RescheduleLaterDay: 'reschedule_later_day'
} as const;

export type JobRequestAbsenceResolvedJobAlternativeKindEnum = typeof JobRequestAbsenceResolvedJobAlternativeKindEnum[keyof typeof JobRequestAbsenceResolvedJobAlternativeKindEnum];
export const JobRequestAbsenceResolvedJobPriorityEnum = {
    P0: 'p0',
    P1: 'p1',
    P2: 'p2',
    P3: 'p3'
} as const;

export type JobRequestAbsenceResolvedJobPriorityEnum = typeof JobRequestAbsenceResolvedJobPriorityEnum[keyof typeof JobRequestAbsenceResolvedJobPriorityEnum];


