/* tslint:disable */
/* eslint-disable */
/**
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { JobRequestSession } from './job-request-session';

/**
 * 
 * @export
 * @interface JobRequestTechCandidate
 */
export interface JobRequestTechCandidate {
    /**
     * Minutes of job work already booked on this technician\'s schedule over the evaluated window (feeds the wrench-time score; lower = more open capacity).
     * @type {number}
     * @memberof JobRequestTechCandidate
     */
    'booked_minutes'?: number;
    /**
     * Estimated one-way distance from the technician\'s start location to the job site, in km (routing-provider estimate, straight-line fallback). 0 when the job has no geocoded location.
     * @type {number}
     * @memberof JobRequestTechCandidate
     */
    'distance_km'?: number;
    /**
     * Technician\'s full display name.
     * @type {string}
     * @memberof JobRequestTechCandidate
     */
    'full_name'?: string;
    /**
     * How many of the job\'s desired skills this technician holds.
     * @type {number}
     * @memberof JobRequestTechCandidate
     */
    'matched_skills'?: number;
    /**
     * Per-day on-site session plan this technician would work for the job (ordered; one block for a single-day visit, several for multi-day).
     * @type {Array<JobRequestSession>}
     * @memberof JobRequestTechCandidate
     */
    'sessions'?: Array<JobRequestSession>;
    /**
     * UUID of the candidate technician.
     * @type {string}
     * @memberof JobRequestTechCandidate
     */
    'technician_id'?: string;
    /**
     * Overall ranking score (0-100): weighted blend of the distance, travel-time, wrench-time and skill sub-scores; candidates are listed best-first.
     * @type {number}
     * @memberof JobRequestTechCandidate
     */
    'total_score'?: number;
    /**
     * Estimated one-way travel time from the technician\'s start location to the job site, in minutes. 0 when the job has no geocoded location.
     * @type {number}
     * @memberof JobRequestTechCandidate
     */
    'travel_minutes'?: number;
}

