/* tslint:disable */
/* eslint-disable */
/**
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { JobRequestTimelineAction } from './job-request-timeline-action';

/**
 * 
 * @export
 * @interface JobRequestTimelineEvent
 */
export interface JobRequestTimelineEvent {
    /**
     * Actions declared for this status, in workflow order. Omitted when none.
     * @type {Array<JobRequestTimelineAction>}
     * @memberof JobRequestTimelineEvent
     */
    'actions'?: Array<JobRequestTimelineAction>;
    /**
     * Status display name, resolved to the request locale.
     * @type {string}
     * @memberof JobRequestTimelineEvent
     */
    'display_name'?: string;
    /**
     * When the job entered this status (UTC); null for upcoming steps or jobs missing the backfill.
     * @type {string}
     * @memberof JobRequestTimelineEvent
     */
    'entered_at'?: string;
    /**
     * Where this status sits relative to the job\'s progress.
     * @type {string}
     * @memberof JobRequestTimelineEvent
     */
    'state'?: JobRequestTimelineEventStateEnum;
    /**
     * Workflow status key for this row.
     * @type {string}
     * @memberof JobRequestTimelineEvent
     */
    'status_key'?: string;
}

export const JobRequestTimelineEventStateEnum = {
    Completed: 'completed',
    Current: 'current',
    Upcoming: 'upcoming'
} as const;

export type JobRequestTimelineEventStateEnum = typeof JobRequestTimelineEventStateEnum[keyof typeof JobRequestTimelineEventStateEnum];


