/* tslint:disable */
/* eslint-disable */
/**
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { JobRequestBlockerRef } from './job-request-blocker-ref';

/**
 * 
 * @export
 * @interface JobRequestBlocker
 */
export interface JobRequestBlocker {
    /**
     * occupied: the short code of the job holding the window.
     * @type {string}
     * @memberof JobRequestBlocker
     */
    'conflict_short_code'?: string;
    /**
     * cannot_arrive_in_time: first same-day instant (UTC) the technician CAN be on site.
     * @type {string}
     * @memberof JobRequestBlocker
     */
    'earliest_feasible_at'?: string;
    /**
     * on_time_off (the approved leave) / occupied (the conflicting window) — window start, UTC.
     * @type {string}
     * @memberof JobRequestBlocker
     */
    'from'?: string;
    /**
     * outside_service_area: the service area the job sits in.
     * @type {JobRequestBlockerRef}
     * @memberof JobRequestBlocker
     */
    'job_area'?: JobRequestBlockerRef;
    /**
     * Which hard filter refused the technician.
     * @type {string}
     * @memberof JobRequestBlocker
     */
    'kind'?: JobRequestBlockerKindEnum;
    /**
     * visit_too_long: the maximum a single visit may run, in minutes.
     * @type {number}
     * @memberof JobRequestBlocker
     */
    'max_minutes'?: number;
    /**
     * missing_required_skills: the job\'s skills this technician lacks (never the full required list).
     * @type {Array<JobRequestBlockerRef>}
     * @memberof JobRequestBlocker
     */
    'missing'?: Array<JobRequestBlockerRef>;
    /**
     * off_shift: see shift_start_minute.
     * @type {number}
     * @memberof JobRequestBlocker
     */
    'shift_end_minute'?: number;
    /**
     * off_shift: the technician\'s working window that business-local day, minutes from midnight — 0 is a legal start-of-day value (see the platform\'s minutes-since-midnight convention), so both fields are present together whenever off_shift applies, and both absent (never a serialised 0) on no_working_day, where there is no window at all.
     * @type {number}
     * @memberof JobRequestBlocker
     */
    'shift_start_minute'?: number;
    /**
     * outside_service_area: the areas this technician is actually assigned to.
     * @type {Array<JobRequestBlockerRef>}
     * @memberof JobRequestBlocker
     */
    'tech_areas'?: Array<JobRequestBlockerRef>;
    /**
     * on_time_off / occupied — window end, UTC.
     * @type {string}
     * @memberof JobRequestBlocker
     */
    'to'?: string;
    /**
     * visit_too_long: the visit\'s own length, in minutes.
     * @type {number}
     * @memberof JobRequestBlocker
     */
    'visit_minutes'?: number;
}

export const JobRequestBlockerKindEnum = {
    OutsideServiceArea: 'outside_service_area',
    MissingRequiredSkills: 'missing_required_skills',
    NotLeadTier: 'not_lead_tier',
    NoWorkingDay: 'no_working_day',
    OnTimeOff: 'on_time_off',
    OffShift: 'off_shift',
    Occupied: 'occupied',
    VisitTooLong: 'visit_too_long',
    CannotArriveInTime: 'cannot_arrive_in_time'
} as const;

export type JobRequestBlockerKindEnum = typeof JobRequestBlockerKindEnum[keyof typeof JobRequestBlockerKindEnum];


