/* tslint:disable */
/* eslint-disable */
/**
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface JobRequestMovePreviewReq
 */
export interface JobRequestMovePreviewReq {
    /**
     * Cascade mode for displaced jobs: overtime = stay same-day (tech works late); next_day = overflow rolls to the next working day.
     * @type {string}
     * @memberof JobRequestMovePreviewReq
     */
    'mode': JobRequestMovePreviewReqModeEnum;
    /**
     * New start — business-local naive datetime, no offset. Must be in the future.
     * @type {string}
     * @memberof JobRequestMovePreviewReq
     */
    'start_at': string;
    /**
     * Target technician — may equal the current tech (pure time move) or differ (manual reassign).
     * @type {string}
     * @memberof JobRequestMovePreviewReq
     */
    'technician_id': string;
}

export const JobRequestMovePreviewReqModeEnum = {
    Overtime: 'overtime',
    NextDay: 'next_day'
} as const;

export type JobRequestMovePreviewReqModeEnum = typeof JobRequestMovePreviewReqModeEnum[keyof typeof JobRequestMovePreviewReqModeEnum];


