/* tslint:disable */
/* eslint-disable */
/**
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { JobRequestTimeSegmentsDay } from './job-request-time-segments-day';

/**
 * 
 * @export
 * @interface JobRequestTimeSegments
 */
export interface JobRequestTimeSegments {
    /**
     * UUID of the business the job belongs to.
     * @type {string}
     * @memberof JobRequestTimeSegments
     */
    'business_id'?: string;
    /**
     * Business display name.
     * @type {string}
     * @memberof JobRequestTimeSegments
     */
    'business_name'?: string;
    /**
     * IANA timezone of the business (business_time values render in this zone).
     * @type {string}
     * @memberof JobRequestTimeSegments
     */
    'business_timezone'?: string;
    /**
     * IANA timezone of the customer (customer-facing slot times render in this zone).
     * @type {string}
     * @memberof JobRequestTimeSegments
     */
    'customer_timezone'?: string;
    /**
     * Offerable days in date order, each with its slot grid. Only future slots with at least one feasible technician are offered.
     * @type {Array<JobRequestTimeSegmentsDay>}
     * @memberof JobRequestTimeSegments
     */
    'days'?: Array<JobRequestTimeSegmentsDay>;
    /**
     * True when the customer\'s originally chosen dates yield NO offerable slot — either they are already in the past, or no technician is available on them. `days` then holds fresh SUGGESTED days instead: the same time-of-day periods, scanned from the day after their last chosen date (never before today) across at most 7 days, offering the first 3 days that have availability (may be empty when nothing was found — tell the customer no alternative exists within the week). The FE should surface that their chosen dates didn\'t work out and these are new suggestions.
     * @type {boolean}
     * @memberof JobRequestTimeSegments
     */
    'is_suggested'?: boolean;
    /**
     * Job identifier — the human-readable short code when present, else the job UUID.
     * @type {string}
     * @memberof JobRequestTimeSegments
     */
    'job_request_id'?: string;
    /**
     * Slot granularity in minutes (the arrival-window width). Defaults to the business\'s configured arrival window; clamped to 5-240.
     * @type {number}
     * @memberof JobRequestTimeSegments
     */
    'time_slot_step_minutes'?: number;
}

