/* tslint:disable */
/* eslint-disable */
/**
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface JobTypeCreateRequest
 */
export interface JobTypeCreateRequest {
    /**
     * Default demobilization (teardown) minutes, 0–1440; used together with the default duration. Requires a default duration. Omit or 0 = no default.
     * @type {number}
     * @memberof JobTypeCreateRequest
     */
    'default_demobilization_minutes'?: number;
    /**
     * Default hands-on work duration in minutes for this kind of work (1–20160). A quote that sends no job_duration_minutes uses it, which is what lets an automation or voice agent schedule a job without knowing how long the work takes. Omit or 0 = no default.
     * @type {number}
     * @memberof JobTypeCreateRequest
     */
    'default_duration_minutes'?: number;
    /**
     * Default mobilization (setup/travel-prep) minutes, 0–1440; used together with the default duration. Requires a default duration. Omit or 0 = no default.
     * @type {number}
     * @memberof JobTypeCreateRequest
     */
    'default_mobilization_minutes'?: number;
    /**
     * Job-type name (required) — what the booking form shows as the kind of work. Stored as the canonical English value; per-locale names are a dashboard authoring feature.
     * @type {string}
     * @memberof JobTypeCreateRequest
     */
    'name': string;
    /**
     * Lifecycle status. Defaults to active; inactive types cannot be selected for new job requests.
     * @type {string}
     * @memberof JobTypeCreateRequest
     */
    'status'?: JobTypeCreateRequestStatusEnum;
}

export const JobTypeCreateRequestStatusEnum = {
    Active: 'active',
    Inactive: 'inactive'
} as const;

export type JobTypeCreateRequestStatusEnum = typeof JobTypeCreateRequestStatusEnum[keyof typeof JobTypeCreateRequestStatusEnum];


