/* tslint:disable */
/* eslint-disable */
/**
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { JobRequestJobDatePeriodRequest } from './job-request-job-date-period-request';

/**
 * 
 * @export
 * @interface JobRequestJobDateRequest
 */
export interface JobRequestJobDateRequest {
    /**
     * Requested calendar day (YYYY-MM-DD), customer-local. Required.
     * @type {string}
     * @memberof JobRequestJobDateRequest
     */
    'date': string;
    /**
     * One or more time-of-day periods requested on this date. At least one, up to 3.
     * @type {Array<JobRequestJobDatePeriodRequest>}
     * @memberof JobRequestJobDateRequest
     */
    'periods': Array<JobRequestJobDatePeriodRequest>;
}

