/* tslint:disable */
/* eslint-disable */
/**
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface JobRequestSession
 */
export interface JobRequestSession {
    /**
     * Calendar day (YYYY-MM-DD) this session falls on, business-local.
     * @type {string}
     * @memberof JobRequestSession
     */
    'date'?: string;
    /**
     * Leave-home time bracketing the day: StartAt minus planned travel (UTC). Omitted (with return_at) when travel is unknown.
     * @type {string}
     * @memberof JobRequestSession
     */
    'depart_at'?: string;
    /**
     * Leave site — end of demobilization (UTC).
     * @type {string}
     * @memberof JobRequestSession
     */
    'end_at'?: string;
    /**
     * 1-based day index within the job\'s span (1 for single-day jobs).
     * @type {number}
     * @memberof JobRequestSession
     */
    'ordinal'?: number;
    /**
     * Arrive-home time bracketing the day: EndAt plus planned travel (UTC). Omitted (with depart_at) when travel is unknown.
     * @type {string}
     * @memberof JobRequestSession
     */
    'return_at'?: string;
    /**
     * On-site arrival — start of mobilization (UTC).
     * @type {string}
     * @memberof JobRequestSession
     */
    'start_at'?: string;
    /**
     * TravelMinutes is the PLANNED one-way commute (home → site) for this day, snapshotted at assignment. Omitted when unknown (admin-fallback job with no geocoded location, or legacy row).
     * @type {number}
     * @memberof JobRequestSession
     */
    'travel_minutes'?: number;
}

