/* tslint:disable */
/* eslint-disable */
/**
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface JobRequestEmergencyPreviewRequest
 */
export interface JobRequestEmergencyPreviewRequest {
    /**
     * Place this P0 outside working hours / approved time-off — you have phoned the technician and they agreed. Drops the non-working-day rejection; the response then carries an AFTER_HOURS warning. Double-booking, service area, required skills and the lead-tier rule still reject.
     * @type {boolean}
     * @memberof JobRequestEmergencyPreviewRequest
     */
    'after_hours_override'?: boolean;
    /**
     * Fate of displaced jobs: reschedule (default — pushed to later windows) or reassign (handed to another feasible technician at their ORIGINAL time; no-capacity jobs fall back to reschedule).
     * @type {string}
     * @memberof JobRequestEmergencyPreviewRequest
     */
    'displacement_mode'?: JobRequestEmergencyPreviewRequestDisplacementModeEnum;
    /**
     * ID of the P0 job to insert.
     * @type {string}
     * @memberof JobRequestEmergencyPreviewRequest
     */
    'emergency_job_id': string;
    /**
     * Cascade mode: overtime = displaced jobs stay same-day (tech works late); next_day = overflow rolls to the next working day.
     * @type {string}
     * @memberof JobRequestEmergencyPreviewRequest
     */
    'mode': JobRequestEmergencyPreviewRequestModeEnum;
    /**
     * Desired start — business-local wall clock. Seconds may be omitted and a space may replace the T; an offset is accepted only when it agrees with the business timezone (a disagreeing one is refused with JOB_REQUEST_INVALID_INPUT rather than guessed). Must be in the future.
     * @type {string}
     * @memberof JobRequestEmergencyPreviewRequest
     */
    'start_at': string;
    /**
     * Target technician (must belong to the business).
     * @type {string}
     * @memberof JobRequestEmergencyPreviewRequest
     */
    'technician_id': string;
}

export const JobRequestEmergencyPreviewRequestDisplacementModeEnum = {
    Reschedule: 'reschedule',
    Reassign: 'reassign'
} as const;

export type JobRequestEmergencyPreviewRequestDisplacementModeEnum = typeof JobRequestEmergencyPreviewRequestDisplacementModeEnum[keyof typeof JobRequestEmergencyPreviewRequestDisplacementModeEnum];
export const JobRequestEmergencyPreviewRequestModeEnum = {
    Overtime: 'overtime',
    NextDay: 'next_day'
} as const;

export type JobRequestEmergencyPreviewRequestModeEnum = typeof JobRequestEmergencyPreviewRequestModeEnum[keyof typeof JobRequestEmergencyPreviewRequestModeEnum];


