/* tslint:disable */
/* eslint-disable */
/**
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NearbyTechnician
 */
export interface NearbyTechnician {
    /**
     * Minutes already booked that day (workload context).
     * @type {number}
     * @memberof NearbyTechnician
     */
    'booked_minutes'?: number;
    /**
     * Estimated distance from the tech\'s start location to the site, in kilometers.
     * @type {number}
     * @memberof NearbyTechnician
     */
    'distance_km'?: number;
    /**
     * Candidate technician\'s full name. Omitted when unresolved.
     * @type {string}
     * @memberof NearbyTechnician
     */
    'full_name'?: string;
    /**
     * Number of desired skills the tech matches (when skill_ids sent).
     * @type {number}
     * @memberof NearbyTechnician
     */
    'matched_skills'?: number;
    /**
     * UUID of the candidate technician.
     * @type {string}
     * @memberof NearbyTechnician
     */
    'technician_id'?: string;
    /**
     * Assignment tier (lead | buddy | float).
     * @type {string}
     * @memberof NearbyTechnician
     */
    'tier'?: NearbyTechnicianTierEnum;
    /**
     * Smart-assign engine ranking score (higher = better fit).
     * @type {number}
     * @memberof NearbyTechnician
     */
    'total_score'?: number;
    /**
     * ETA estimate in minutes from the tech\'s start location (static origin — no live GPS; a ranking hint, not a promise).
     * @type {number}
     * @memberof NearbyTechnician
     */
    'travel_minutes'?: number;
}

export const NearbyTechnicianTierEnum = {
    Lead: 'lead',
    Buddy: 'buddy',
    Float: 'float'
} as const;

export type NearbyTechnicianTierEnum = typeof NearbyTechnicianTierEnum[keyof typeof NearbyTechnicianTierEnum];


