/* tslint:disable */
/* eslint-disable */
/**
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ServiceArea
 */
export interface ServiceArea {
    /**
     * GeoJSON polygon boundary of the area; null if no boundary was set.
     * @type {object}
     * @memberof ServiceArea
     */
    'boundary'?: object;
    /**
     * UUID of the business that owns this service area.
     * @type {string}
     * @memberof ServiceArea
     */
    'business_id'?: string;
    /**
     * City / locality for the area. Empty if unused.
     * @type {string}
     * @memberof ServiceArea
     */
    'city'?: string;
    /**
     * County for the area. Empty if unused.
     * @type {string}
     * @memberof ServiceArea
     */
    'county'?: string;
    /**
     * When the service area was created (RFC3339).
     * @type {string}
     * @memberof ServiceArea
     */
    'created_at'?: string;
    /**
     * Free-form description of the area. Empty if none was set.
     * @type {string}
     * @memberof ServiceArea
     */
    'description'?: string;
    /**
     * District for the area. Empty if unused.
     * @type {string}
     * @memberof ServiceArea
     */
    'district'?: string;
    /**
     * Service-area UUID — the stable identifier used in every service-area endpoint.
     * @type {string}
     * @memberof ServiceArea
     */
    'id'?: string;
    /**
     * Service-area display name.
     * @type {string}
     * @memberof ServiceArea
     */
    'name'?: string;
    /**
     * Postal / ZIP code for the area. Empty if unused.
     * @type {string}
     * @memberof ServiceArea
     */
    'postal_code'?: string;
    /**
     * When the service area was last modified (RFC3339).
     * @type {string}
     * @memberof ServiceArea
     */
    'updated_at'?: string;
}

