/* tslint:disable */
/* eslint-disable */
/**
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TechnicianTimeOffCreateRequest
 */
export interface TechnicianTimeOffCreateRequest {
    /**
     * Block end — RFC3339 instant, must be after start_datetime. A whole day off runs local midnight to the next.
     * @type {string}
     * @memberof TechnicianTimeOffCreateRequest
     */
    'end_datetime': string;
    /**
     * Free-text reason, max 500 characters (e.g. \"Sick call 06:58\").
     * @type {string}
     * @memberof TechnicianTimeOffCreateRequest
     */
    'reason'?: string;
    /**
     * Block start — an RFC3339 instant WITH offset (e.g. 2030-06-15T04:00:00Z = midnight Toronto EDT), not a business-local naive datetime.
     * @type {string}
     * @memberof TechnicianTimeOffCreateRequest
     */
    'start_datetime': string;
    /**
     * The technician taking time off (must belong to the business).
     * @type {string}
     * @memberof TechnicianTimeOffCreateRequest
     */
    'technician_id': string;
}

