/* tslint:disable */
/* eslint-disable */
/**
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TechnicianScheduleSession
 */
export interface TechnicianScheduleSession {
    /**
     * Session window end (UTC).
     * @type {string}
     * @memberof TechnicianScheduleSession
     */
    'end_at'?: string;
    /**
     * UUID of the occupying job request.
     * @type {string}
     * @memberof TechnicianScheduleSession
     */
    'job_id'?: string;
    /**
     * Priority of the occupying job (p0..p3).
     * @type {string}
     * @memberof TechnicianScheduleSession
     */
    'priority'?: TechnicianScheduleSessionPriorityEnum;
    /**
     * lead = single-person job; crew = a multi-person job this technician is a member of (the specific member role is not distinguished here).
     * @type {string}
     * @memberof TechnicianScheduleSession
     */
    'role'?: TechnicianScheduleSessionRoleEnum;
    /**
     * Human-readable job code (e.g. \"REQ-A3K7M2X9\").
     * @type {string}
     * @memberof TechnicianScheduleSession
     */
    'short_code'?: string;
    /**
     * Session window start (UTC).
     * @type {string}
     * @memberof TechnicianScheduleSession
     */
    'start_at'?: string;
}

export const TechnicianScheduleSessionPriorityEnum = {
    P0: 'p0',
    P1: 'p1',
    P2: 'p2',
    P3: 'p3'
} as const;

export type TechnicianScheduleSessionPriorityEnum = typeof TechnicianScheduleSessionPriorityEnum[keyof typeof TechnicianScheduleSessionPriorityEnum];
export const TechnicianScheduleSessionRoleEnum = {
    Lead: 'lead',
    Crew: 'crew'
} as const;

export type TechnicianScheduleSessionRoleEnum = typeof TechnicianScheduleSessionRoleEnum[keyof typeof TechnicianScheduleSessionRoleEnum];


