/* tslint:disable */
/* eslint-disable */
/**
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TechnicianAddressInput } from './technician-address-input';

/**
 * 
 * @export
 * @interface TechnicianCreateRequest
 */
export interface TechnicianCreateRequest {
    /**
     * Home address (the day-start point when start_location_type=home).
     * @type {TechnicianAddressInput}
     * @memberof TechnicianCreateRequest
     */
    'address'?: TechnicianAddressInput;
    /**
     * Crew tier the matching engine assigns by: lead (can head a job), buddy (crew helper), float (excluded from auto crew-assign).
     * @type {string}
     * @memberof TechnicianCreateRequest
     */
    'assignment_tier'?: TechnicianCreateRequestAssignmentTierEnum;
    /**
     * Buddies of this technician (set when creating a lead). Optional; max 50 technician ids.
     * @type {Array<string>}
     * @memberof TechnicianCreateRequest
     */
    'buddy_ids'?: Array<string>;
    /**
     * Role group for the new member. Discover IDs via GET /permission/groups (Owner/Administrator groups are rejected in sandbox mode).
     * @type {string}
     * @memberof TechnicianCreateRequest
     */
    'business_group_id': string;
    /**
     * Email address. At least one of phone/email is required (identity resolution key).
     * @type {string}
     * @memberof TechnicianCreateRequest
     */
    'email'?: string;
    /**
     * The person\'s full display name. Required; max 255 chars.
     * @type {string}
     * @memberof TechnicianCreateRequest
     */
    'full_name': string;
    /**
     * Display title (e.g. \"Senior HVAC Technician\").
     * @type {string}
     * @memberof TechnicianCreateRequest
     */
    'job_title'?: string;
    /**
     * First working day (YYYY-MM-DD).
     * @type {string}
     * @memberof TechnicianCreateRequest
     */
    'join_date'?: string;
    /**
     * Leads this technician is a buddy of (set when creating a buddy; the technician is appended to each lead\'s buddy list). Optional; max 50 technician ids.
     * @type {Array<string>}
     * @memberof TechnicianCreateRequest
     */
    'lead_ids'?: Array<string>;
    /**
     * At least one of phone/email is required (identity resolution key).
     * @type {string}
     * @memberof TechnicianCreateRequest
     */
    'phone'?: string;
    /**
     * Service areas to assign the technician to. Optional; max 50. Discover via GET /service-areas.
     * @type {Array<string>}
     * @memberof TechnicianCreateRequest
     */
    'service_area_ids'?: Array<string>;
    /**
     * Explicit day-start latitude in decimal degrees (-90..90); when set it wins over the address geocode.
     * @type {number}
     * @memberof TechnicianCreateRequest
     */
    'start_location_lat'?: number;
    /**
     * Explicit day-start longitude in decimal degrees (-180..180); when set it wins over the address geocode.
     * @type {number}
     * @memberof TechnicianCreateRequest
     */
    'start_location_long'?: number;
    /**
     * Where the technician starts their day: home (their address) or office (the business location). Drives the engine\'s travel estimates.
     * @type {string}
     * @memberof TechnicianCreateRequest
     */
    'start_location_type'?: TechnicianCreateRequestStartLocationTypeEnum;
}

export const TechnicianCreateRequestAssignmentTierEnum = {
    Lead: 'lead',
    Buddy: 'buddy',
    Float: 'float'
} as const;

export type TechnicianCreateRequestAssignmentTierEnum = typeof TechnicianCreateRequestAssignmentTierEnum[keyof typeof TechnicianCreateRequestAssignmentTierEnum];
export const TechnicianCreateRequestStartLocationTypeEnum = {
    Home: 'home',
    Office: 'office'
} as const;

export type TechnicianCreateRequestStartLocationTypeEnum = typeof TechnicianCreateRequestStartLocationTypeEnum[keyof typeof TechnicianCreateRequestStartLocationTypeEnum];


