/* tslint:disable */
/* eslint-disable */
/**
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface VehicleUpdateRequest
 */
export interface VehicleUpdateRequest {
    /**
     * nil = keep; \"\" clears the field.
     * @type {string}
     * @memberof VehicleUpdateRequest
     */
    'brand'?: string;
    /**
     * 
     * @type {number}
     * @memberof VehicleUpdateRequest
     */
    'current_mileage'?: number;
    /**
     * 
     * @type {string}
     * @memberof VehicleUpdateRequest
     */
    'model'?: string;
    /**
     * nil = keep. min=1 rejects an explicit \"\" (a vehicle needs a name); omitempty is what lets a nil pointer skip validation entirely.
     * @type {string}
     * @memberof VehicleUpdateRequest
     */
    'name'?: string;
    /**
     * nil = keep the current owner; \"\" clears it; a UUID sets it.
     * @type {string}
     * @memberof VehicleUpdateRequest
     */
    'owner_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof VehicleUpdateRequest
     */
    'plate_number'?: string;
    /**
     * 
     * @type {string}
     * @memberof VehicleUpdateRequest
     */
    'status'?: VehicleUpdateRequestStatusEnum;
    /**
     * nil = keep; a non-nil value must be a known enum member.
     * @type {string}
     * @memberof VehicleUpdateRequest
     */
    'vehicle_type'?: VehicleUpdateRequestVehicleTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof VehicleUpdateRequest
     */
    'year'?: number;
}

export const VehicleUpdateRequestStatusEnum = {
    Inactive: 'inactive',
    Idle: 'idle',
    OnJob: 'on_job',
    Maintenance: 'maintenance'
} as const;

export type VehicleUpdateRequestStatusEnum = typeof VehicleUpdateRequestStatusEnum[keyof typeof VehicleUpdateRequestStatusEnum];
export const VehicleUpdateRequestVehicleTypeEnum = {
    Van: 'van',
    Truck: 'truck',
    Car: 'car'
} as const;

export type VehicleUpdateRequestVehicleTypeEnum = typeof VehicleUpdateRequestVehicleTypeEnum[keyof typeof VehicleUpdateRequestVehicleTypeEnum];


