/* tslint:disable */
/* eslint-disable */
/**
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface VehicleCreateRequest
 */
export interface VehicleCreateRequest {
    /**
     * Manufacturer / make. Optional.
     * @type {string}
     * @memberof VehicleCreateRequest
     */
    'brand'?: string;
    /**
     * Odometer reading. Optional; must be >= 0 when sent.
     * @type {number}
     * @memberof VehicleCreateRequest
     */
    'current_mileage'?: number;
    /**
     * Model name. Optional.
     * @type {string}
     * @memberof VehicleCreateRequest
     */
    'model'?: string;
    /**
     * Vehicle display name (required). The only mandatory field — a fleet import needs nothing but names to get vehicles into the system.
     * @type {string}
     * @memberof VehicleCreateRequest
     */
    'name': string;
    /**
     * UUID of the technician who owns (has claimed) this vehicle. Optional. The owner must be a lead technician or a management role — a buddy- or float-tier profile is refused with VEHICLE_OWNER_TIER_NOT_ALLOWED. Assigning which vehicles a technician USES is a different relation: PUT /technicians/{id}/vehicles.
     * @type {string}
     * @memberof VehicleCreateRequest
     */
    'owner_id'?: string;
    /**
     * License plate. Optional.
     * @type {string}
     * @memberof VehicleCreateRequest
     */
    'plate_number'?: string;
    /**
     * 
     * @type {string}
     * @memberof VehicleCreateRequest
     */
    'vehicle_type'?: VehicleCreateRequestVehicleTypeEnum;
    /**
     * Model year. Optional.
     * @type {number}
     * @memberof VehicleCreateRequest
     */
    'year'?: number;
}

export const VehicleCreateRequestVehicleTypeEnum = {
    Van: 'van',
    Truck: 'truck',
    Car: 'car'
} as const;

export type VehicleCreateRequestVehicleTypeEnum = typeof VehicleCreateRequestVehicleTypeEnum[keyof typeof VehicleCreateRequestVehicleTypeEnum];


