/* tslint:disable */
/* eslint-disable */
/**
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WebhookCreateRequest
 */
export interface WebhookCreateRequest {
    /**
     * Optional human label shown in the dashboard.
     * @type {string}
     * @memberof WebhookCreateRequest
     */
    'description'?: string;
    /**
     * Event types to receive. Empty = ALL events. See GET /business/webhooks/event-types.
     * @type {Array<string>}
     * @memberof WebhookCreateRequest
     */
    'event_types'?: Array<string>;
    /**
     * Signing-secret lifetime in days. Omit for the 30-day default; 1..365 to choose your own. When it lapses the endpoint stops delivering until you rotate — see POST /business/webhooks/{id}/rotate-secret.
     * @type {number}
     * @memberof WebhookCreateRequest
     */
    'expires_in_days'?: number;
    /**
     * HTTPS callback URL Crisphive will POST events to. Required; absolute http(s).
     * @type {string}
     * @memberof WebhookCreateRequest
     */
    'url': string;
}

